
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package exp.fluffynuar.truedarkness.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import exp.fluffynuar.truedarkness.block.WoodenMugBlock;
import exp.fluffynuar.truedarkness.block.WasterFlowerBlock;
import exp.fluffynuar.truedarkness.block.WastelandSheafStairsBlock;
import exp.fluffynuar.truedarkness.block.WastelandSheafSlabBlock;
import exp.fluffynuar.truedarkness.block.WastelandSheafFenceBlock;
import exp.fluffynuar.truedarkness.block.WastelandSheafBlock;
import exp.fluffynuar.truedarkness.block.WastelandBushBlock;
import exp.fluffynuar.truedarkness.block.UndeskyBlacksoilBlock;
import exp.fluffynuar.truedarkness.block.UnclearSandOfMissingBlock;
import exp.fluffynuar.truedarkness.block.UnclearRenteriaSandBlock;
import exp.fluffynuar.truedarkness.block.UnclearDeepslateSandBlock;
import exp.fluffynuar.truedarkness.block.TrudniteOreBlock;
import exp.fluffynuar.truedarkness.block.TrudniteBlockBlock;
import exp.fluffynuar.truedarkness.block.TrapSandOfMissingBlock;
import exp.fluffynuar.truedarkness.block.TallLavenderBlock;
import exp.fluffynuar.truedarkness.block.SwampTerracotaBlock;
import exp.fluffynuar.truedarkness.block.SwampTallGrassBlock;
import exp.fluffynuar.truedarkness.block.SwampSunflowerBlock;
import exp.fluffynuar.truedarkness.block.SwampStoneWallBlock;
import exp.fluffynuar.truedarkness.block.SwampStoneStairsBlock;
import exp.fluffynuar.truedarkness.block.SwampStoneSlabBlock;
import exp.fluffynuar.truedarkness.block.SwampStoneBlock;
import exp.fluffynuar.truedarkness.block.SwampStarGrassBlock;
import exp.fluffynuar.truedarkness.block.SwampSoilBlock;
import exp.fluffynuar.truedarkness.block.SwampSeaweedBlock;
import exp.fluffynuar.truedarkness.block.SwampSandLayerBlock;
import exp.fluffynuar.truedarkness.block.SwampSandLayer2Block;
import exp.fluffynuar.truedarkness.block.SwampSandLayer1Block;
import exp.fluffynuar.truedarkness.block.SwampSandBlock;
import exp.fluffynuar.truedarkness.block.SwampMudBlock;
import exp.fluffynuar.truedarkness.block.SwampLilyBlock;
import exp.fluffynuar.truedarkness.block.SwampKelpTopBlock;
import exp.fluffynuar.truedarkness.block.SwampGrassBlock;
import exp.fluffynuar.truedarkness.block.SwampDirtBlock;
import exp.fluffynuar.truedarkness.block.SwampDeadGrassBlock;
import exp.fluffynuar.truedarkness.block.SwampCobblestoneWallBlock;
import exp.fluffynuar.truedarkness.block.SwampCobblestoneStairsBlock;
import exp.fluffynuar.truedarkness.block.SwampCobblestoneSlabBlock;
import exp.fluffynuar.truedarkness.block.SwampCobblestoneBlock;
import exp.fluffynuar.truedarkness.block.SwampClayBlock;
import exp.fluffynuar.truedarkness.block.SwampChamomileBlock;
import exp.fluffynuar.truedarkness.block.SwampBushBlock;
import exp.fluffynuar.truedarkness.block.SwampBricksWallBlock;
import exp.fluffynuar.truedarkness.block.SwampBricksStairsBlock;
import exp.fluffynuar.truedarkness.block.SwampBricksSlabBlock;
import exp.fluffynuar.truedarkness.block.SwampBricksBlock;
import exp.fluffynuar.truedarkness.block.SwampBlackSoilBlock;
import exp.fluffynuar.truedarkness.block.SuspiciousRenteriaSandBlock;
import exp.fluffynuar.truedarkness.block.StrippedNeaskyWoodBlock;
import exp.fluffynuar.truedarkness.block.StrippedNeaskyLogBlock;
import exp.fluffynuar.truedarkness.block.StrippedGlowWoodBlock;
import exp.fluffynuar.truedarkness.block.StrippedGlowLogBlock;
import exp.fluffynuar.truedarkness.block.StrippedFakeWoodBlock;
import exp.fluffynuar.truedarkness.block.StrippedFakeLogBlock;
import exp.fluffynuar.truedarkness.block.StrippedDarknessSpruceLogBlock;
import exp.fluffynuar.truedarkness.block.StrippedDarknessSpruceBlock;
import exp.fluffynuar.truedarkness.block.StrippedCyanWoodBlock;
import exp.fluffynuar.truedarkness.block.StrippedCyanLogBlock;
import exp.fluffynuar.truedarkness.block.StrippedCryingWoodBlock;
import exp.fluffynuar.truedarkness.block.StrippedCryingLogBlock;
import exp.fluffynuar.truedarkness.block.StarTeleporterBlock;
import exp.fluffynuar.truedarkness.block.SporeVine2Block;
import exp.fluffynuar.truedarkness.block.SoulstealGridBlock;
import exp.fluffynuar.truedarkness.block.SoulstealBlockBlock;
import exp.fluffynuar.truedarkness.block.SmallSkullBlock;
import exp.fluffynuar.truedarkness.block.SkystarSmallRootsBlock;
import exp.fluffynuar.truedarkness.block.SkystarRootsBlock;
import exp.fluffynuar.truedarkness.block.SkystarLargeFernBlock;
import exp.fluffynuar.truedarkness.block.SkystarGrassBlock;
import exp.fluffynuar.truedarkness.block.SkystarFlowersBlock;
import exp.fluffynuar.truedarkness.block.SkystarFernBlock;
import exp.fluffynuar.truedarkness.block.SkyfallOreBlock;
import exp.fluffynuar.truedarkness.block.ShiseledSwampBricksBlock;
import exp.fluffynuar.truedarkness.block.ShaddyMelonBlock;
import exp.fluffynuar.truedarkness.block.SeekerPlantTopBlock;
import exp.fluffynuar.truedarkness.block.SeekerPlantGlowTopBlock;
import exp.fluffynuar.truedarkness.block.SeekerPlantGlowBlock;
import exp.fluffynuar.truedarkness.block.SeekerPlantBlock;
import exp.fluffynuar.truedarkness.block.SculkSoilBlock;
import exp.fluffynuar.truedarkness.block.SandstoneOfMissingWallBlock;
import exp.fluffynuar.truedarkness.block.SandstoneOfMissingStairsBlock;
import exp.fluffynuar.truedarkness.block.SandstoneOfMissingSlabBlock;
import exp.fluffynuar.truedarkness.block.SandstoneOfMissingBlock;
import exp.fluffynuar.truedarkness.block.SandOfMissingLayerBlock;
import exp.fluffynuar.truedarkness.block.SandOfMissingLayer2Block;
import exp.fluffynuar.truedarkness.block.SandOfMissingLayer1Block;
import exp.fluffynuar.truedarkness.block.SandOfMissingIronOreBlock;
import exp.fluffynuar.truedarkness.block.SandOfMissingBlock;
import exp.fluffynuar.truedarkness.block.SamovarBlock;
import exp.fluffynuar.truedarkness.block.SamovarActiveBlock;
import exp.fluffynuar.truedarkness.block.RunedSwampStoneBlock;
import exp.fluffynuar.truedarkness.block.RenteriaSandBlock;
import exp.fluffynuar.truedarkness.block.RecraGrassBlock;
import exp.fluffynuar.truedarkness.block.RecraFlower1Block;
import exp.fluffynuar.truedarkness.block.PurulentSpruceLogBlock;
import exp.fluffynuar.truedarkness.block.ProectorBlock;
import exp.fluffynuar.truedarkness.block.PrismarinumCoralWaveBlock;
import exp.fluffynuar.truedarkness.block.PrismarinumCoralRichBlock;
import exp.fluffynuar.truedarkness.block.PrismarinumCoralFlashingBlock;
import exp.fluffynuar.truedarkness.block.PrismarinumCoralDarknessBlock;
import exp.fluffynuar.truedarkness.block.PrismarinumCoralColourlessBlock;
import exp.fluffynuar.truedarkness.block.PrismarineCoralWaveBlock;
import exp.fluffynuar.truedarkness.block.PrismarineCoralRichBlock;
import exp.fluffynuar.truedarkness.block.PrismarineCoralFlashingBlock;
import exp.fluffynuar.truedarkness.block.PrismarineCoralDarknessBlock;
import exp.fluffynuar.truedarkness.block.PrismarineCoralColourlessBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampStoneWallBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampStoneStairsBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampStoneSlabBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampStoneBricksWallBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampStoneBricksStairsBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampStoneBricksSlabBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampStoneBricksBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampStoneBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampCobblestoneWallBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampCobblestoneStairsBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampCobblestoneSlabBlock;
import exp.fluffynuar.truedarkness.block.PolishedSwampCobblestoneBlock;
import exp.fluffynuar.truedarkness.block.PolishedSandstoneOfMissingStairsBlock;
import exp.fluffynuar.truedarkness.block.PolishedSandstoneOfMissingSlabBlock;
import exp.fluffynuar.truedarkness.block.PolishedSandstoneOfMissingBlock;
import exp.fluffynuar.truedarkness.block.PolishedSandstoneBricksOfMissingWallBlock;
import exp.fluffynuar.truedarkness.block.PolishedSandstoneBricksOfMissingStairsBlock;
import exp.fluffynuar.truedarkness.block.PolishedSandstoneBricksOfMissingSlabBlock;
import exp.fluffynuar.truedarkness.block.PolishedSandstoneBricksOfMissingBlock;
import exp.fluffynuar.truedarkness.block.PolishedAccustoneWallBlock;
import exp.fluffynuar.truedarkness.block.PolishedAccustoneStairsBlock;
import exp.fluffynuar.truedarkness.block.PolishedAccustoneSlabBlock;
import exp.fluffynuar.truedarkness.block.PolishedAccustoneBricksWallBlock;
import exp.fluffynuar.truedarkness.block.PolishedAccustoneBricksStairsBlock;
import exp.fluffynuar.truedarkness.block.PolishedAccustoneBricksSlabBlock;
import exp.fluffynuar.truedarkness.block.PolishedAccustoneBricksBlock;
import exp.fluffynuar.truedarkness.block.PolishedAccustoneBlock;
import exp.fluffynuar.truedarkness.block.PoisonerBlock;
import exp.fluffynuar.truedarkness.block.NeaskyWoodBlock;
import exp.fluffynuar.truedarkness.block.NeaskyVinesBlock;
import exp.fluffynuar.truedarkness.block.NeaskyTrapDoorBlock;
import exp.fluffynuar.truedarkness.block.NeaskyStairsBlock;
import exp.fluffynuar.truedarkness.block.NeaskySlabBlock;
import exp.fluffynuar.truedarkness.block.NeaskyPumpkinBlock;
import exp.fluffynuar.truedarkness.block.NeaskyPressurePlateBlock;
import exp.fluffynuar.truedarkness.block.NeaskyPlanksBlock;
import exp.fluffynuar.truedarkness.block.NeaskyLogBlock;
import exp.fluffynuar.truedarkness.block.NeaskyLeavesBlock;
import exp.fluffynuar.truedarkness.block.NeaskyFenceGateBlock;
import exp.fluffynuar.truedarkness.block.NeaskyFenceBlock;
import exp.fluffynuar.truedarkness.block.NeaskyDoorBlock;
import exp.fluffynuar.truedarkness.block.NeaskyButtonBlock;
import exp.fluffynuar.truedarkness.block.MyceliumRootsBlock;
import exp.fluffynuar.truedarkness.block.MyceliumGrassBlock;
import exp.fluffynuar.truedarkness.block.MossySwampBricksBlock;
import exp.fluffynuar.truedarkness.block.MossyPolishedSwampStoneBricksBlock;
import exp.fluffynuar.truedarkness.block.MossyPolishedAccustoneBricksBlock;
import exp.fluffynuar.truedarkness.block.MossyDarknessSprucePlanksBlock;
import exp.fluffynuar.truedarkness.block.MossyCorruptedBricksBlock;
import exp.fluffynuar.truedarkness.block.MeteniteGlassPaneBlock;
import exp.fluffynuar.truedarkness.block.MeteniteGlassBlock;
import exp.fluffynuar.truedarkness.block.MeteniteClusterBlock;
import exp.fluffynuar.truedarkness.block.MeteniteBlockBlock;
import exp.fluffynuar.truedarkness.block.MeaskyTreeBlock;
import exp.fluffynuar.truedarkness.block.MeaskyMossBlock;
import exp.fluffynuar.truedarkness.block.MeaskyLeavesBlock;
import exp.fluffynuar.truedarkness.block.MeaskyCarpetBlock;
import exp.fluffynuar.truedarkness.block.LightedVine2Block;
import exp.fluffynuar.truedarkness.block.LightedShroom1Block;
import exp.fluffynuar.truedarkness.block.LightShroomBlock;
import exp.fluffynuar.truedarkness.block.LightShroom3Block;
import exp.fluffynuar.truedarkness.block.LightShroom2Block;
import exp.fluffynuar.truedarkness.block.LightOfSoulBlock;
import exp.fluffynuar.truedarkness.block.LightMushroomsDisableBlock;
import exp.fluffynuar.truedarkness.block.LightMushroomsActiveBlock;
import exp.fluffynuar.truedarkness.block.LightMushroomTopBlock;
import exp.fluffynuar.truedarkness.block.LightMushroomTop1Block;
import exp.fluffynuar.truedarkness.block.LightMushroomTallBlock;
import exp.fluffynuar.truedarkness.block.LightFungusBlockBlock;
import exp.fluffynuar.truedarkness.block.LavenderBlock;
import exp.fluffynuar.truedarkness.block.LapisLazuliSwampOreBlock;
import exp.fluffynuar.truedarkness.block.KettleForSamoverBlock;
import exp.fluffynuar.truedarkness.block.KettleBlock;
import exp.fluffynuar.truedarkness.block.JumpTestBlockBlock;
import exp.fluffynuar.truedarkness.block.IgnimeOreBlock;
import exp.fluffynuar.truedarkness.block.IceTestBlockBlock;
import exp.fluffynuar.truedarkness.block.GrapeAzaleaLeavesBlock;
import exp.fluffynuar.truedarkness.block.GlowniteTrapDoorBlock;
import exp.fluffynuar.truedarkness.block.GlowniteStairsBlock;
import exp.fluffynuar.truedarkness.block.GlowniteSlabBlock;
import exp.fluffynuar.truedarkness.block.GlowniteGridPaneBlock;
import exp.fluffynuar.truedarkness.block.GlowniteGridLanternBlock;
import exp.fluffynuar.truedarkness.block.GlowniteGridBlock;
import exp.fluffynuar.truedarkness.block.GlowniteDoorBlock;
import exp.fluffynuar.truedarkness.block.GlowniteBricksStairsBlock;
import exp.fluffynuar.truedarkness.block.GlowniteBricksSlabBlock;
import exp.fluffynuar.truedarkness.block.GlowniteBricksBlock;
import exp.fluffynuar.truedarkness.block.GlowniteBlockBlock;
import exp.fluffynuar.truedarkness.block.GlowWoodBlock;
import exp.fluffynuar.truedarkness.block.GlowTrapDoorBlock;
import exp.fluffynuar.truedarkness.block.GlowStairsBlock;
import exp.fluffynuar.truedarkness.block.GlowSlabBlock;
import exp.fluffynuar.truedarkness.block.GlowPressurePlateBlock;
import exp.fluffynuar.truedarkness.block.GlowPlanksBlock;
import exp.fluffynuar.truedarkness.block.GlowLogBlock;
import exp.fluffynuar.truedarkness.block.GlowFungusHatBlock;
import exp.fluffynuar.truedarkness.block.GlowFenceGateBlock;
import exp.fluffynuar.truedarkness.block.GlowFenceBlock;
import exp.fluffynuar.truedarkness.block.GlowDoorBlock;
import exp.fluffynuar.truedarkness.block.GlowButtonBlock;
import exp.fluffynuar.truedarkness.block.GlassJarBlock;
import exp.fluffynuar.truedarkness.block.FireniteBlockBlock;
import exp.fluffynuar.truedarkness.block.FirefliesFlowerBlock;
import exp.fluffynuar.truedarkness.block.FakeWoodBlock;
import exp.fluffynuar.truedarkness.block.FakeTrapDoorBlock;
import exp.fluffynuar.truedarkness.block.FakeStairsBlock;
import exp.fluffynuar.truedarkness.block.FakeSlabBlock;
import exp.fluffynuar.truedarkness.block.FakePressurePlateBlock;
import exp.fluffynuar.truedarkness.block.FakePlanksBlock;
import exp.fluffynuar.truedarkness.block.FakeLogBlock;
import exp.fluffynuar.truedarkness.block.FakeLeavesBlock;
import exp.fluffynuar.truedarkness.block.FakeFenceGateBlock;
import exp.fluffynuar.truedarkness.block.FakeFenceBlock;
import exp.fluffynuar.truedarkness.block.FakeDoorBlock;
import exp.fluffynuar.truedarkness.block.FakeButtonBlock;
import exp.fluffynuar.truedarkness.block.FakeBoxBlock;
import exp.fluffynuar.truedarkness.block.EridiumGlassPaneBlock;
import exp.fluffynuar.truedarkness.block.EridiumGlassBlock;
import exp.fluffynuar.truedarkness.block.EridiumClusterBlock;
import exp.fluffynuar.truedarkness.block.EridiumBlockBlock;
import exp.fluffynuar.truedarkness.block.EmptyChiseledGlassPaneBlock;
import exp.fluffynuar.truedarkness.block.EmptyChiseledGlassBlock;
import exp.fluffynuar.truedarkness.block.EmptyChiseledAncientGlassPaneBlock;
import exp.fluffynuar.truedarkness.block.EmptyChiseledAncientGlassBlock;
import exp.fluffynuar.truedarkness.block.EchoMasterBlock;
import exp.fluffynuar.truedarkness.block.DustClayWallBlock;
import exp.fluffynuar.truedarkness.block.DustClayStairsBlock;
import exp.fluffynuar.truedarkness.block.DustClaySlabBlock;
import exp.fluffynuar.truedarkness.block.DustClayBricksWallBlock;
import exp.fluffynuar.truedarkness.block.DustClayBricksStairsBlock;
import exp.fluffynuar.truedarkness.block.DustClayBricksSlabBlock;
import exp.fluffynuar.truedarkness.block.DustClayBricksBlock;
import exp.fluffynuar.truedarkness.block.DustClayBlock;
import exp.fluffynuar.truedarkness.block.DustBlockBlock;
import exp.fluffynuar.truedarkness.block.DriedSwampBushBlock;
import exp.fluffynuar.truedarkness.block.DeadPrismarineCoralWaveBlock;
import exp.fluffynuar.truedarkness.block.DeadPrismarineCoralRichBlock;
import exp.fluffynuar.truedarkness.block.DeadPrismarineCoralFlashingBlock;
import exp.fluffynuar.truedarkness.block.DeadPrismarineCoralDarknessBlock;
import exp.fluffynuar.truedarkness.block.DeadPrismarineCoralColourlessBlock;
import exp.fluffynuar.truedarkness.block.DeadGrassBlock;
import exp.fluffynuar.truedarkness.block.DeadBushSwampBlock;
import exp.fluffynuar.truedarkness.block.DarkniteWallBlock;
import exp.fluffynuar.truedarkness.block.DarkniteStairsBlock;
import exp.fluffynuar.truedarkness.block.DarkniteSlabBlock;
import exp.fluffynuar.truedarkness.block.DarkniteBricksWallBlock;
import exp.fluffynuar.truedarkness.block.DarkniteBricksStairsBlock;
import exp.fluffynuar.truedarkness.block.DarkniteBricksSlabBlock;
import exp.fluffynuar.truedarkness.block.DarkniteBricksBlock;
import exp.fluffynuar.truedarkness.block.DarkniteBlock;
import exp.fluffynuar.truedarkness.block.DarknessStainedPaneBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceWoodBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceTrapDoorBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceStairsBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceSlabBlock;
import exp.fluffynuar.truedarkness.block.DarknessSprucePressurePlateBlock;
import exp.fluffynuar.truedarkness.block.DarknessSprucePlanksBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceLogBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceFenceGateBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceFenceBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceDoorBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceChestBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceButtonBlock;
import exp.fluffynuar.truedarkness.block.DarknessSpruceBoxBlock;
import exp.fluffynuar.truedarkness.block.DarknessGlassBlock;
import exp.fluffynuar.truedarkness.block.DarkCrystalBlockBlock;
import exp.fluffynuar.truedarkness.block.CyanWoodBlock;
import exp.fluffynuar.truedarkness.block.CyanTrapDoorBlock;
import exp.fluffynuar.truedarkness.block.CyanStairsBlock;
import exp.fluffynuar.truedarkness.block.CyanSlabBlock;
import exp.fluffynuar.truedarkness.block.CyanPressurePlateBlock;
import exp.fluffynuar.truedarkness.block.CyanPlanksBlock;
import exp.fluffynuar.truedarkness.block.CyanLogBlock;
import exp.fluffynuar.truedarkness.block.CyanLeavesBlock;
import exp.fluffynuar.truedarkness.block.CyanFenceGateBlock;
import exp.fluffynuar.truedarkness.block.CyanFenceBlock;
import exp.fluffynuar.truedarkness.block.CyanDoorBlock;
import exp.fluffynuar.truedarkness.block.CyanButtonBlock;
import exp.fluffynuar.truedarkness.block.CyanBookshelfBlock;
import exp.fluffynuar.truedarkness.block.CvetaliyOreBlock;
import exp.fluffynuar.truedarkness.block.CvetaliyClusterBlock;
import exp.fluffynuar.truedarkness.block.CvetaliyBlockBlock;
import exp.fluffynuar.truedarkness.block.CursedWorkbenchBlock;
import exp.fluffynuar.truedarkness.block.CursedScaleBlock;
import exp.fluffynuar.truedarkness.block.CursedPipeBlock;
import exp.fluffynuar.truedarkness.block.CursedLecternBlock;
import exp.fluffynuar.truedarkness.block.CursedFurnaceBlock;
import exp.fluffynuar.truedarkness.block.CursedCauldronBlock;
import exp.fluffynuar.truedarkness.block.CursedBookshelfBlock;
import exp.fluffynuar.truedarkness.block.CursedAnvilBlock;
import exp.fluffynuar.truedarkness.block.CryingWoodBlock;
import exp.fluffynuar.truedarkness.block.CryingTrapDoorBlock;
import exp.fluffynuar.truedarkness.block.CryingStairsBlock;
import exp.fluffynuar.truedarkness.block.CryingSlabBlock;
import exp.fluffynuar.truedarkness.block.CryingPressurePlateBlock;
import exp.fluffynuar.truedarkness.block.CryingPlanksBlock;
import exp.fluffynuar.truedarkness.block.CryingLogBlock;
import exp.fluffynuar.truedarkness.block.CryingLeavesBlock;
import exp.fluffynuar.truedarkness.block.CryingFenceGateBlock;
import exp.fluffynuar.truedarkness.block.CryingFenceBlock;
import exp.fluffynuar.truedarkness.block.CryingDoorBlock;
import exp.fluffynuar.truedarkness.block.CryingButtonBlock;
import exp.fluffynuar.truedarkness.block.CryBlockBlock;
import exp.fluffynuar.truedarkness.block.CrenritBlock;
import exp.fluffynuar.truedarkness.block.CrackedSwampBricksBlock;
import exp.fluffynuar.truedarkness.block.CrackedSandstoneBricksOfMissingBlock;
import exp.fluffynuar.truedarkness.block.CrackedPolishedSwampStoneBricksBlock;
import exp.fluffynuar.truedarkness.block.CrackedPolishedAccustoneBricksBlock;
import exp.fluffynuar.truedarkness.block.CrackedDarkniteBricksBlock;
import exp.fluffynuar.truedarkness.block.CrackedAccuswampMosaicWallBlock;
import exp.fluffynuar.truedarkness.block.CrackedAccuswampMosaicStairsBlock;
import exp.fluffynuar.truedarkness.block.CrackedAccuswampMosaicSlabBlock;
import exp.fluffynuar.truedarkness.block.CrackedAccuswampMosaicBlock;
import exp.fluffynuar.truedarkness.block.CorruptyRootsSmallBlock;
import exp.fluffynuar.truedarkness.block.CorruptyRootsBlock;
import exp.fluffynuar.truedarkness.block.CorruptyLeavesFlowerBlock;
import exp.fluffynuar.truedarkness.block.CorruptyLeavesBlock;
import exp.fluffynuar.truedarkness.block.CorruptedVines2Block;
import exp.fluffynuar.truedarkness.block.CorruptedSunflowerBlock;
import exp.fluffynuar.truedarkness.block.CorruptedSoilBlock;
import exp.fluffynuar.truedarkness.block.CorruptedSlimeBlock;
import exp.fluffynuar.truedarkness.block.CorruptedSkulkCatalystBlock;
import exp.fluffynuar.truedarkness.block.CorruptedSculkCatalystBloomingBlock;
import exp.fluffynuar.truedarkness.block.CorruptedSculkBlock;
import exp.fluffynuar.truedarkness.block.CorruptedRuneBlock;
import exp.fluffynuar.truedarkness.block.CorruptedRootsBlock;
import exp.fluffynuar.truedarkness.block.CorruptedReactorBlock;
import exp.fluffynuar.truedarkness.block.CorruptedLightBlock;
import exp.fluffynuar.truedarkness.block.CorruptedLeavesBlock;
import exp.fluffynuar.truedarkness.block.CorruptedLanternBlock;
import exp.fluffynuar.truedarkness.block.CorruptedKnightRemnantsBlock;
import exp.fluffynuar.truedarkness.block.CorruptedGrassBlockBlock;
import exp.fluffynuar.truedarkness.block.CorruptedGrassBlock;
import exp.fluffynuar.truedarkness.block.CorruptedFlowerBlock;
import exp.fluffynuar.truedarkness.block.CorruptedCampfireBlock;
import exp.fluffynuar.truedarkness.block.CorruptedBushBlock;
import exp.fluffynuar.truedarkness.block.CorruptedBubbleEmptyBlock;
import exp.fluffynuar.truedarkness.block.CorruptedBubbleBlockBlock;
import exp.fluffynuar.truedarkness.block.CorruptRuneBlock;
import exp.fluffynuar.truedarkness.block.CorruptRune2Block;
import exp.fluffynuar.truedarkness.block.CorruptRune1Block;
import exp.fluffynuar.truedarkness.block.CorruptBricksWallBlock;
import exp.fluffynuar.truedarkness.block.CorruptBricksStairsBlock;
import exp.fluffynuar.truedarkness.block.CorruptBricksSlabBlock;
import exp.fluffynuar.truedarkness.block.CorruptBricksBlock;
import exp.fluffynuar.truedarkness.block.CorruptBlock;
import exp.fluffynuar.truedarkness.block.Corrupt1Block;
import exp.fluffynuar.truedarkness.block.Corrupt0Block;
import exp.fluffynuar.truedarkness.block.CopperKettleForSamovarBlock;
import exp.fluffynuar.truedarkness.block.CopperKettleBlock;
import exp.fluffynuar.truedarkness.block.CobbledDarkniteWallBlock;
import exp.fluffynuar.truedarkness.block.CobbledDarkniteStairsBlock;
import exp.fluffynuar.truedarkness.block.CobbledDarkniteSlabBlock;
import exp.fluffynuar.truedarkness.block.CobbledDarkniteBlock;
import exp.fluffynuar.truedarkness.block.CobbledAccustoneWallBlock;
import exp.fluffynuar.truedarkness.block.CobbledAccustoneStairsBlock;
import exp.fluffynuar.truedarkness.block.CobbledAccustoneSlabBlock;
import exp.fluffynuar.truedarkness.block.CobbledAccustoneBlock;
import exp.fluffynuar.truedarkness.block.ChiseledPolishedSandstoneBricksOfMissingBlock;
import exp.fluffynuar.truedarkness.block.ChiseledPolishedAccustoneBricksBlock;
import exp.fluffynuar.truedarkness.block.ChiseledGlowniteStairsBlock;
import exp.fluffynuar.truedarkness.block.ChiseledGlowniteSlabBlock;
import exp.fluffynuar.truedarkness.block.ChiseledGlowniteBlock;
import exp.fluffynuar.truedarkness.block.ChiseledGlassPaneBlock;
import exp.fluffynuar.truedarkness.block.ChiseledGlassPane4Block;
import exp.fluffynuar.truedarkness.block.ChiseledGlassPane3Block;
import exp.fluffynuar.truedarkness.block.ChiseledGlassPane2Block;
import exp.fluffynuar.truedarkness.block.ChiseledGlassPane1Block;
import exp.fluffynuar.truedarkness.block.ChiseledGlassBlock;
import exp.fluffynuar.truedarkness.block.ChiseledGlass4Block;
import exp.fluffynuar.truedarkness.block.ChiseledGlass3Block;
import exp.fluffynuar.truedarkness.block.ChiseledGlass2Block;
import exp.fluffynuar.truedarkness.block.ChiseledGlass1Block;
import exp.fluffynuar.truedarkness.block.ChiseledDarkniteBricksBlock;
import exp.fluffynuar.truedarkness.block.ChiseledCorruptedBricksBlock;
import exp.fluffynuar.truedarkness.block.BushyGrapeAzaleaLeavesBlock;
import exp.fluffynuar.truedarkness.block.BushedPolishedSandstoneBricksOfMissingBlock;
import exp.fluffynuar.truedarkness.block.BubbleBlock;
import exp.fluffynuar.truedarkness.block.BloomingCryingLaevesBlock;
import exp.fluffynuar.truedarkness.block.BloodContainerBlock;
import exp.fluffynuar.truedarkness.block.BlinkRootsBlock;
import exp.fluffynuar.truedarkness.block.BlinkMushroomHatBlock;
import exp.fluffynuar.truedarkness.block.BlacksmiteForgeBlock;
import exp.fluffynuar.truedarkness.block.BigGlowniteBricksStairsBlock;
import exp.fluffynuar.truedarkness.block.BigGlowniteBricksSlabBlock;
import exp.fluffynuar.truedarkness.block.BigGlowniteBricksBlock;
import exp.fluffynuar.truedarkness.block.BagBlock;
import exp.fluffynuar.truedarkness.block.AncientSculkBlock;
import exp.fluffynuar.truedarkness.block.AccuswampMosaicWallBlock;
import exp.fluffynuar.truedarkness.block.AccuswampMosaicStairsBlock;
import exp.fluffynuar.truedarkness.block.AccuswampMosaicSlabBlock;
import exp.fluffynuar.truedarkness.block.AccuswampMosaicBlock;
import exp.fluffynuar.truedarkness.TruedarknessMod;

public class TruedarknessModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, TruedarknessMod.MODID);
	public static final RegistryObject<Block> SWAMP_STONE = REGISTRY.register("swamp_stone", () -> new SwampStoneBlock());
	public static final RegistryObject<Block> SWAMP_DIRT = REGISTRY.register("swamp_dirt", () -> new SwampDirtBlock());
	public static final RegistryObject<Block> SWAMP_BLACK_SOIL = REGISTRY.register("swamp_black_soil", () -> new SwampBlackSoilBlock());
	public static final RegistryObject<Block> SWAMP_LILY = REGISTRY.register("swamp_lily", () -> new SwampLilyBlock());
	public static final RegistryObject<Block> SWAMP_SUNFLOWER = REGISTRY.register("swamp_sunflower", () -> new SwampSunflowerBlock());
	public static final RegistryObject<Block> SWAMP_CHAMOMILE = REGISTRY.register("swamp_chamomile", () -> new SwampChamomileBlock());
	public static final RegistryObject<Block> SWAMP_GRASS = REGISTRY.register("swamp_grass", () -> new SwampGrassBlock());
	public static final RegistryObject<Block> SWAMP_SAND = REGISTRY.register("swamp_sand", () -> new SwampSandBlock());
	public static final RegistryObject<Block> CORRUPT = REGISTRY.register("corrupt", () -> new CorruptBlock());
	public static final RegistryObject<Block> CORRUPTED_FLOWER = REGISTRY.register("corrupted_flower", () -> new CorruptedFlowerBlock());
	public static final RegistryObject<Block> CORRUPTED_GRASS = REGISTRY.register("corrupted_grass", () -> new CorruptedGrassBlock());
	public static final RegistryObject<Block> FIRENITE_BLOCK = REGISTRY.register("firenite_block", () -> new FireniteBlockBlock());
	public static final RegistryObject<Block> DEAD_BUSH_SWAMP = REGISTRY.register("dead_bush_swamp", () -> new DeadBushSwampBlock());
	public static final RegistryObject<Block> CORRUPTED_RUNE = REGISTRY.register("corrupted_rune", () -> new CorruptedRuneBlock());
	public static final RegistryObject<Block> LAPIS_LAZULI_SWAMP_ORE = REGISTRY.register("lapis_lazuli_swamp_ore", () -> new LapisLazuliSwampOreBlock());
	public static final RegistryObject<Block> CYAN = REGISTRY.register("cyan", () -> new CyanWoodBlock());
	public static final RegistryObject<Block> CYAN_STEM = REGISTRY.register("cyan_stem", () -> new CyanLogBlock());
	public static final RegistryObject<Block> CYAN_PLANKS = REGISTRY.register("cyan_planks", () -> new CyanPlanksBlock());
	public static final RegistryObject<Block> CYAN_PETAL = REGISTRY.register("cyan_petal", () -> new CyanLeavesBlock());
	public static final RegistryObject<Block> CYAN_STAIRS = REGISTRY.register("cyan_stairs", () -> new CyanStairsBlock());
	public static final RegistryObject<Block> CYAN_SLAB = REGISTRY.register("cyan_slab", () -> new CyanSlabBlock());
	public static final RegistryObject<Block> CYAN_FENCE = REGISTRY.register("cyan_fence", () -> new CyanFenceBlock());
	public static final RegistryObject<Block> CYAN_FENCE_GATE = REGISTRY.register("cyan_fence_gate", () -> new CyanFenceGateBlock());
	public static final RegistryObject<Block> CYAN_PRESSURE_PLATE = REGISTRY.register("cyan_pressure_plate", () -> new CyanPressurePlateBlock());
	public static final RegistryObject<Block> CYAN_BUTTON = REGISTRY.register("cyan_button", () -> new CyanButtonBlock());
	public static final RegistryObject<Block> CYAN_DOOR = REGISTRY.register("cyan_door", () -> new CyanDoorBlock());
	public static final RegistryObject<Block> CYAN_TRAP_DOOR = REGISTRY.register("cyan_trap_door", () -> new CyanTrapDoorBlock());
	public static final RegistryObject<Block> CYAN_BOOKSHELF = REGISTRY.register("cyan_bookshelf", () -> new CyanBookshelfBlock());
	public static final RegistryObject<Block> CORRUPTED_SUNFLOWER = REGISTRY.register("corrupted_sunflower", () -> new CorruptedSunflowerBlock());
	public static final RegistryObject<Block> SWAMP_SOIL = REGISTRY.register("swamp_soil", () -> new SwampSoilBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_WOOD = REGISTRY.register("darkness_spruce_wood", () -> new DarknessSpruceWoodBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_LOG = REGISTRY.register("darkness_spruce_log", () -> new DarknessSpruceLogBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_PLANKS = REGISTRY.register("darkness_spruce_planks", () -> new DarknessSprucePlanksBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_STAIRS = REGISTRY.register("darkness_spruce_stairs", () -> new DarknessSpruceStairsBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_SLAB = REGISTRY.register("darkness_spruce_slab", () -> new DarknessSpruceSlabBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_FENCE = REGISTRY.register("darkness_spruce_fence", () -> new DarknessSpruceFenceBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_FENCE_GATE = REGISTRY.register("darkness_spruce_fence_gate", () -> new DarknessSpruceFenceGateBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_PRESSURE_PLATE = REGISTRY.register("darkness_spruce_pressure_plate", () -> new DarknessSprucePressurePlateBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_BUTTON = REGISTRY.register("darkness_spruce_button", () -> new DarknessSpruceButtonBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_DOOR = REGISTRY.register("darkness_spruce_door", () -> new DarknessSpruceDoorBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_TRAP_DOOR = REGISTRY.register("darkness_spruce_trap_door", () -> new DarknessSpruceTrapDoorBlock());
	public static final RegistryObject<Block> SWAMP_COBBLESTONE = REGISTRY.register("swamp_cobblestone", () -> new SwampCobblestoneBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_COBBLESTONE = REGISTRY.register("polished_swamp_cobblestone", () -> new PolishedSwampCobblestoneBlock());
	public static final RegistryObject<Block> SWAMP_BRICKS = REGISTRY.register("swamp_bricks", () -> new SwampBricksBlock());
	public static final RegistryObject<Block> CRACKED_SWAMP_BRICKS = REGISTRY.register("cracked_swamp_bricks", () -> new CrackedSwampBricksBlock());
	public static final RegistryObject<Block> MOSSY_SWAMP_BRICKS = REGISTRY.register("mossy_swamp_bricks", () -> new MossySwampBricksBlock());
	public static final RegistryObject<Block> SWAMP_BRICKS_STAIRS = REGISTRY.register("swamp_bricks_stairs", () -> new SwampBricksStairsBlock());
	public static final RegistryObject<Block> SWAMP_BRICKS_SLAB = REGISTRY.register("swamp_bricks_slab", () -> new SwampBricksSlabBlock());
	public static final RegistryObject<Block> SWAMP_BRICKS_WALL = REGISTRY.register("swamp_bricks_wall", () -> new SwampBricksWallBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_COBBLESTONE_STAIRS = REGISTRY.register("polished_swamp_cobblestone_stairs", () -> new PolishedSwampCobblestoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_COBBLESTONE_SLAB = REGISTRY.register("polished_swamp_cobblestone_slab", () -> new PolishedSwampCobblestoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_COBBLESTONE_WALL = REGISTRY.register("polished_swamp_cobblestone_wall", () -> new PolishedSwampCobblestoneWallBlock());
	public static final RegistryObject<Block> CHISELED_SWAMP_BRICKS = REGISTRY.register("chiseled_swamp_bricks", () -> new ShiseledSwampBricksBlock());
	public static final RegistryObject<Block> CHISELED_ANCIENT_GLASS = REGISTRY.register("chiseled_ancient_glass", () -> new DarknessGlassBlock());
	public static final RegistryObject<Block> CHISELED_ANCIENT_GLASS_PANE = REGISTRY.register("chiseled_ancient_glass_pane", () -> new DarknessStainedPaneBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_CHEST = REGISTRY.register("darkness_spruce_chest", () -> new DarknessSpruceChestBlock());
	public static final RegistryObject<Block> DRIED_SWAMP_BUSH = REGISTRY.register("dried_swamp_bush", () -> new DriedSwampBushBlock());
	public static final RegistryObject<Block> DUST_BLOCK = REGISTRY.register("dust_block", () -> new DustBlockBlock());
	public static final RegistryObject<Block> ERIDIUM_GLASS = REGISTRY.register("eridium_glass", () -> new EridiumGlassBlock());
	public static final RegistryObject<Block> ERIDIUM_GLASS_PANE = REGISTRY.register("eridium_glass_pane", () -> new EridiumGlassPaneBlock());
	public static final RegistryObject<Block> DARKNITE = REGISTRY.register("darknite", () -> new DarkniteBlock());
	public static final RegistryObject<Block> COBBLED_DARKNITE = REGISTRY.register("cobbled_darknite", () -> new CobbledDarkniteBlock());
	public static final RegistryObject<Block> DARKNITE_BRICKS = REGISTRY.register("darknite_bricks", () -> new DarkniteBricksBlock());
	public static final RegistryObject<Block> BLACKSMITE_FORGE = REGISTRY.register("blacksmite_forge", () -> new BlacksmiteForgeBlock());
	public static final RegistryObject<Block> CVETALIY_ORE = REGISTRY.register("cvetaliy_ore", () -> new CvetaliyOreBlock());
	public static final RegistryObject<Block> GLOW_FUNGUS_0 = REGISTRY.register("glow_fungus_0", () -> new LightShroomBlock());
	public static final RegistryObject<Block> GLOW_FUNGUS_1 = REGISTRY.register("glow_fungus_1", () -> new LightedShroom1Block());
	public static final RegistryObject<Block> GLOW_FUNGUS_2 = REGISTRY.register("glow_fungus_2", () -> new LightShroom2Block());
	public static final RegistryObject<Block> LIGHT_SHROOM_3 = REGISTRY.register("light_shroom_3", () -> new LightShroom3Block());
	public static final RegistryObject<Block> SWAMP_MUD = REGISTRY.register("swamp_mud", () -> new SwampMudBlock());
	public static final RegistryObject<Block> SWAMP_TERRACOTA = REGISTRY.register("swamp_terracota", () -> new SwampTerracotaBlock());
	public static final RegistryObject<Block> LAVENDER = REGISTRY.register("lavender", () -> new LavenderBlock());
	public static final RegistryObject<Block> TALL_LAVENDER = REGISTRY.register("tall_lavender", () -> new TallLavenderBlock());
	public static final RegistryObject<Block> MOSSY_DARKNESS_SPRUCE_PLANKS = REGISTRY.register("mossy_darkness_spruce_planks", () -> new MossyDarknessSprucePlanksBlock());
	public static final RegistryObject<Block> CORRUPTED_LEAF = REGISTRY.register("corrupted_leaf", () -> new CorruptedLeavesBlock());
	public static final RegistryObject<Block> CORRUPTED_SCULK_CATALYST = REGISTRY.register("corrupted_sculk_catalyst", () -> new CorruptedSkulkCatalystBlock());
	public static final RegistryObject<Block> FIREFLIES_FLOWER = REGISTRY.register("fireflies_flower", () -> new FirefliesFlowerBlock());
	public static final RegistryObject<Block> GRAPE_AZALEA_LEAVES = REGISTRY.register("grape_azalea_leaves", () -> new GrapeAzaleaLeavesBlock());
	public static final RegistryObject<Block> BUSHY_GRAPE_AZALEA_LEAVES = REGISTRY.register("bushy_grape_azalea_leaves", () -> new BushyGrapeAzaleaLeavesBlock());
	public static final RegistryObject<Block> SWAMP_TALL_GRASS = REGISTRY.register("swamp_tall_grass", () -> new SwampTallGrassBlock());
	public static final RegistryObject<Block> SWAMP_BUSH = REGISTRY.register("swamp_bush", () -> new SwampBushBlock());
	public static final RegistryObject<Block> TEAR_BERRY_BLOCK = REGISTRY.register("tear_berry_block", () -> new LightedVine2Block());
	public static final RegistryObject<Block> ANCIENT_SCULK = REGISTRY.register("ancient_sculk", () -> new AncientSculkBlock());
	public static final RegistryObject<Block> SAND_OF_MISSING = REGISTRY.register("sand_of_missing", () -> new SandOfMissingBlock());
	public static final RegistryObject<Block> ERIDIUM_BLOCK = REGISTRY.register("eridium_block", () -> new EridiumBlockBlock());
	public static final RegistryObject<Block> GLASS_JAR = REGISTRY.register("glass_jar", () -> new GlassJarBlock());
	public static final RegistryObject<Block> LIGHT_MUSHROOMS_DISABLE = REGISTRY.register("light_mushrooms_disable", () -> new LightMushroomsDisableBlock());
	public static final RegistryObject<Block> WOODEN_MUG = REGISTRY.register("wooden_mug", () -> new WoodenMugBlock());
	public static final RegistryObject<Block> SAMOVAR = REGISTRY.register("samovar", () -> new SamovarBlock());
	public static final RegistryObject<Block> RUNED_SWAMP_STONE = REGISTRY.register("runed_swamp_stone", () -> new RunedSwampStoneBlock());
	public static final RegistryObject<Block> DARKNITE_STAIRS = REGISTRY.register("darknite_stairs", () -> new DarkniteStairsBlock());
	public static final RegistryObject<Block> DARKNITE_SLAB = REGISTRY.register("darknite_slab", () -> new DarkniteSlabBlock());
	public static final RegistryObject<Block> DARKNITE_WALL = REGISTRY.register("darknite_wall", () -> new DarkniteWallBlock());
	public static final RegistryObject<Block> COBBLED_DARKNITE_STAIRS = REGISTRY.register("cobbled_darknite_stairs", () -> new CobbledDarkniteStairsBlock());
	public static final RegistryObject<Block> COBBLED_DARKNITE_SLAB = REGISTRY.register("cobbled_darknite_slab", () -> new CobbledDarkniteSlabBlock());
	public static final RegistryObject<Block> COBBLED_DARKNITE_WALL = REGISTRY.register("cobbled_darknite_wall", () -> new CobbledDarkniteWallBlock());
	public static final RegistryObject<Block> DARKNITE_BRICKS_STAIRS = REGISTRY.register("darknite_bricks_stairs", () -> new DarkniteBricksStairsBlock());
	public static final RegistryObject<Block> DARKNITE_BRICKS_SLAB = REGISTRY.register("darknite_bricks_slab", () -> new DarkniteBricksSlabBlock());
	public static final RegistryObject<Block> DARKNITE_BRICKS_WALL = REGISTRY.register("darknite_bricks_wall", () -> new DarkniteBricksWallBlock());
	public static final RegistryObject<Block> CRACKED_DARKNITE_BRICKS = REGISTRY.register("cracked_darknite_bricks", () -> new CrackedDarkniteBricksBlock());
	public static final RegistryObject<Block> CHISELED_DARKNITE_BRICKS = REGISTRY.register("chiseled_darknite_bricks", () -> new ChiseledDarkniteBricksBlock());
	public static final RegistryObject<Block> SWAMP_SAND_LAYER = REGISTRY.register("swamp_sand_layer", () -> new SwampSandLayerBlock());
	public static final RegistryObject<Block> SAND_OF_MISSING_LAYER = REGISTRY.register("sand_of_missing_layer", () -> new SandOfMissingLayerBlock());
	public static final RegistryObject<Block> SWAMP_KELP = REGISTRY.register("swamp_kelp", () -> new SwampKelpTopBlock());
	public static final RegistryObject<Block> SWAMP_SEAWEED = REGISTRY.register("swamp_seaweed", () -> new SwampSeaweedBlock());
	public static final RegistryObject<Block> TRAP_SAND_OF_MISSING = REGISTRY.register("trap_sand_of_missing", () -> new TrapSandOfMissingBlock());
	public static final RegistryObject<Block> UNCLEAR_SAND_OF_MISSING = REGISTRY.register("unclear_sand_of_missing", () -> new UnclearSandOfMissingBlock());
	public static final RegistryObject<Block> CHISELED_GLASS = REGISTRY.register("chiseled_glass", () -> new ChiseledGlassBlock());
	public static final RegistryObject<Block> CHISELED_GLASS_1 = REGISTRY.register("chiseled_glass_1", () -> new ChiseledGlass1Block());
	public static final RegistryObject<Block> CHISELED_GLASS_2 = REGISTRY.register("chiseled_glass_2", () -> new ChiseledGlass2Block());
	public static final RegistryObject<Block> CHISELED_GLASS_3 = REGISTRY.register("chiseled_glass_3", () -> new ChiseledGlass3Block());
	public static final RegistryObject<Block> CHISELED_GLASS_4 = REGISTRY.register("chiseled_glass_4", () -> new ChiseledGlass4Block());
	public static final RegistryObject<Block> CHISELED_GLASS_PANE = REGISTRY.register("chiseled_glass_pane", () -> new ChiseledGlassPaneBlock());
	public static final RegistryObject<Block> CHISELED_GLASS_PANE_1 = REGISTRY.register("chiseled_glass_pane_1", () -> new ChiseledGlassPane1Block());
	public static final RegistryObject<Block> CHISELED_GLASS_PANE_2 = REGISTRY.register("chiseled_glass_pane_2", () -> new ChiseledGlassPane2Block());
	public static final RegistryObject<Block> CHISELED_GLASS_PANE_3 = REGISTRY.register("chiseled_glass_pane_3", () -> new ChiseledGlassPane3Block());
	public static final RegistryObject<Block> CHISELED_GLASS_PANE_4 = REGISTRY.register("chiseled_glass_pane_4", () -> new ChiseledGlassPane4Block());
	public static final RegistryObject<Block> EMPTY_CHISELED_GLASS = REGISTRY.register("empty_chiseled_glass", () -> new EmptyChiseledGlassBlock());
	public static final RegistryObject<Block> EMPTY_CHISELED_GLASS_PANE = REGISTRY.register("empty_chiseled_glass_pane", () -> new EmptyChiseledGlassPaneBlock());
	public static final RegistryObject<Block> PROECTOR = REGISTRY.register("proector", () -> new ProectorBlock());
	public static final RegistryObject<Block> DARK_CRYSTAL_CLUSTER_BLOCK = REGISTRY.register("dark_crystal_cluster_block", () -> new DarkCrystalBlockBlock());
	public static final RegistryObject<Block> MYCELIUM_GRASS = REGISTRY.register("mycelium_grass", () -> new MyceliumGrassBlock());
	public static final RegistryObject<Block> MYCELIUM_ROOTS = REGISTRY.register("mycelium_roots", () -> new MyceliumRootsBlock());
	public static final RegistryObject<Block> SANDSTONE_OF_MISSING = REGISTRY.register("sandstone_of_missing", () -> new SandstoneOfMissingBlock());
	public static final RegistryObject<Block> SANDSTONE_OF_MISSING_STAIRS = REGISTRY.register("sandstone_of_missing_stairs", () -> new SandstoneOfMissingStairsBlock());
	public static final RegistryObject<Block> SANDSTONE_OF_MISSING_SLAB = REGISTRY.register("sandstone_of_missing_slab", () -> new SandstoneOfMissingSlabBlock());
	public static final RegistryObject<Block> SANDSTONE_OF_MISSING_WALL = REGISTRY.register("sandstone_of_missing_wall", () -> new SandstoneOfMissingWallBlock());
	public static final RegistryObject<Block> POLISHED_SANDSTONE_OF_MISSING = REGISTRY.register("polished_sandstone_of_missing", () -> new PolishedSandstoneOfMissingBlock());
	public static final RegistryObject<Block> POLISHED_SANDSTONE_OF_MISSING_STAIRS = REGISTRY.register("polished_sandstone_of_missing_stairs", () -> new PolishedSandstoneOfMissingStairsBlock());
	public static final RegistryObject<Block> POLISHED_SANDSTONE_OF_MISSING_SLAB = REGISTRY.register("polished_sandstone_of_missing_slab", () -> new PolishedSandstoneOfMissingSlabBlock());
	public static final RegistryObject<Block> POLISHED_SANDSTONE_OF_MISSING_BRICKS = REGISTRY.register("polished_sandstone_of_missing_bricks", () -> new PolishedSandstoneBricksOfMissingBlock());
	public static final RegistryObject<Block> POLISHED_SANDSTONE_OF_MISSING_BRICKS_STAIRS = REGISTRY.register("polished_sandstone_of_missing_bricks_stairs", () -> new PolishedSandstoneBricksOfMissingStairsBlock());
	public static final RegistryObject<Block> POLISHED_SANDSTONE_OF_MISSING_BRICKS_SLAB = REGISTRY.register("polished_sandstone_of_missing_bricks_slab", () -> new PolishedSandstoneBricksOfMissingSlabBlock());
	public static final RegistryObject<Block> POLISHED_SANDSTONE_OF_MISSING_BRICKS_WALL = REGISTRY.register("polished_sandstone_of_missing_bricks_wall", () -> new PolishedSandstoneBricksOfMissingWallBlock());
	public static final RegistryObject<Block> BUSHED_POLISHED_SANDSTONE_BRICKS_OF_MISSING = REGISTRY.register("bushed_polished_sandstone_bricks_of_missing", () -> new BushedPolishedSandstoneBricksOfMissingBlock());
	public static final RegistryObject<Block> CRACKED_SANDSTONE_BRICKS_OF_MISSING = REGISTRY.register("cracked_sandstone_bricks_of_missing", () -> new CrackedSandstoneBricksOfMissingBlock());
	public static final RegistryObject<Block> CHISELED_POLISHED_SANDSTONE_BRICKS_OF_MISSING = REGISTRY.register("chiseled_polished_sandstone_bricks_of_missing", () -> new ChiseledPolishedSandstoneBricksOfMissingBlock());
	public static final RegistryObject<Block> CVETALIY_BLOCK = REGISTRY.register("cvetaliy_block", () -> new CvetaliyBlockBlock());
	public static final RegistryObject<Block> BAG = REGISTRY.register("bag", () -> new BagBlock());
	public static final RegistryObject<Block> EMPTY_CHISELED_ANCIENT_GLASS = REGISTRY.register("empty_chiseled_ancient_glass", () -> new EmptyChiseledAncientGlassBlock());
	public static final RegistryObject<Block> EMPTY_CHISELED_ANCIENT_GLASS_PANE = REGISTRY.register("empty_chiseled_ancient_glass_pane", () -> new EmptyChiseledAncientGlassPaneBlock());
	public static final RegistryObject<Block> KETTLE = REGISTRY.register("kettle", () -> new KettleBlock());
	public static final RegistryObject<Block> SAMOVAR_ACTIVE = REGISTRY.register("samovar_active", () -> new SamovarActiveBlock());
	public static final RegistryObject<Block> KETTLE_FOR_SAMOVER = REGISTRY.register("kettle_for_samover", () -> new KettleForSamoverBlock());
	public static final RegistryObject<Block> COPPER_KETTLE = REGISTRY.register("copper_kettle", () -> new CopperKettleBlock());
	public static final RegistryObject<Block> COPPER_KETTLE_FOR_SAMOVAR = REGISTRY.register("copper_kettle_for_samovar", () -> new CopperKettleForSamovarBlock());
	public static final RegistryObject<Block> LIGHT_MUSHROOM_TOP = REGISTRY.register("light_mushroom_top", () -> new LightMushroomTopBlock());
	public static final RegistryObject<Block> LIGHT_MUSHROOM_TOP_1 = REGISTRY.register("light_mushroom_top_1", () -> new LightMushroomTop1Block());
	public static final RegistryObject<Block> STRIPPED_DARKNESS_SPRUCE_LOG = REGISTRY.register("stripped_darkness_spruce_log", () -> new StrippedDarknessSpruceLogBlock());
	public static final RegistryObject<Block> STRIPPED_DARKNESS_SPRUCE = REGISTRY.register("stripped_darkness_spruce", () -> new StrippedDarknessSpruceBlock());
	public static final RegistryObject<Block> STRIPPED_CYAN_LOG = REGISTRY.register("stripped_cyan_log", () -> new StrippedCyanLogBlock());
	public static final RegistryObject<Block> STRIPPED_CYAN_WOOD = REGISTRY.register("stripped_cyan_wood", () -> new StrippedCyanWoodBlock());
	public static final RegistryObject<Block> DARKNESS_SPRUCE_BOX = REGISTRY.register("darkness_spruce_box", () -> new DarknessSpruceBoxBlock());
	public static final RegistryObject<Block> LIGHT_MUSHROOM_TALL = REGISTRY.register("light_mushroom_tall", () -> new LightMushroomTallBlock());
	public static final RegistryObject<Block> CORRUPT_RUNE = REGISTRY.register("corrupt_rune", () -> new CorruptRuneBlock());
	public static final RegistryObject<Block> CORRUPT_RUNE_1 = REGISTRY.register("corrupt_rune_1", () -> new CorruptRune1Block());
	public static final RegistryObject<Block> CORRUPT_RUNE_2 = REGISTRY.register("corrupt_rune_2", () -> new CorruptRune2Block());
	public static final RegistryObject<Block> UNCLEAR_CORRUPT = REGISTRY.register("unclear_corrupt", () -> new CorruptedSculkBlock());
	public static final RegistryObject<Block> CRYING_PLANKS = REGISTRY.register("crying_planks", () -> new CryingPlanksBlock());
	public static final RegistryObject<Block> CRYING_STAIRS = REGISTRY.register("crying_stairs", () -> new CryingStairsBlock());
	public static final RegistryObject<Block> CRYING_SLAB = REGISTRY.register("crying_slab", () -> new CryingSlabBlock());
	public static final RegistryObject<Block> CRYING_FENCE = REGISTRY.register("crying_fence", () -> new CryingFenceBlock());
	public static final RegistryObject<Block> CRYING_FENCE_GATE = REGISTRY.register("crying_fence_gate", () -> new CryingFenceGateBlock());
	public static final RegistryObject<Block> CRYING_PRESSURE_PLATE = REGISTRY.register("crying_pressure_plate", () -> new CryingPressurePlateBlock());
	public static final RegistryObject<Block> CRYING_BUTTON = REGISTRY.register("crying_button", () -> new CryingButtonBlock());
	public static final RegistryObject<Block> CRYING_DOOR = REGISTRY.register("crying_door", () -> new CryingDoorBlock());
	public static final RegistryObject<Block> CRYING_TRAP_DOOR = REGISTRY.register("crying_trap_door", () -> new CryingTrapDoorBlock());
	public static final RegistryObject<Block> TRUDNITE_ORE = REGISTRY.register("trudnite_ore", () -> new TrudniteOreBlock());
	public static final RegistryObject<Block> POLISHED_ACCUSTONE = REGISTRY.register("polished_accustone", () -> new PolishedAccustoneBlock());
	public static final RegistryObject<Block> POLISHED_ACCUSTONE_STAIRS = REGISTRY.register("polished_accustone_stairs", () -> new PolishedAccustoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_ACCUSTONE_SLAB = REGISTRY.register("polished_accustone_slab", () -> new PolishedAccustoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_ACCUSTONE_WALL = REGISTRY.register("polished_accustone_wall", () -> new PolishedAccustoneWallBlock());
	public static final RegistryObject<Block> POLISHED_ACCUSTONE_BRICKS = REGISTRY.register("polished_accustone_bricks", () -> new PolishedAccustoneBricksBlock());
	public static final RegistryObject<Block> POLISHED_ACCUSTONE_BRICKS_STAIRS = REGISTRY.register("polished_accustone_bricks_stairs", () -> new PolishedAccustoneBricksStairsBlock());
	public static final RegistryObject<Block> POLISHED_ACCUSTONE_BRICKS_SLAB = REGISTRY.register("polished_accustone_bricks_slab", () -> new PolishedAccustoneBricksSlabBlock());
	public static final RegistryObject<Block> POLISHED_ACCUSTONE_BRICKS_WALL = REGISTRY.register("polished_accustone_bricks_wall", () -> new PolishedAccustoneBricksWallBlock());
	public static final RegistryObject<Block> CRACKED_POLISHED_ACCUSTONE_BRICKS = REGISTRY.register("cracked_polished_accustone_bricks", () -> new CrackedPolishedAccustoneBricksBlock());
	public static final RegistryObject<Block> MOSSY_POLISHED_ACCUSTONE_BRICKS = REGISTRY.register("mossy_polished_accustone_bricks", () -> new MossyPolishedAccustoneBricksBlock());
	public static final RegistryObject<Block> CHISELED_POLISHED_ACCUSTONE_BRICKS = REGISTRY.register("chiseled_polished_accustone_bricks", () -> new ChiseledPolishedAccustoneBricksBlock());
	public static final RegistryObject<Block> TRUDNITE_BLOCK = REGISTRY.register("trudnite_block", () -> new TrudniteBlockBlock());
	public static final RegistryObject<Block> MARINITE_BLOCK = REGISTRY.register("marinite_block", () -> new CryBlockBlock());
	public static final RegistryObject<Block> SWAMP_DEAD_GRASS = REGISTRY.register("swamp_dead_grass", () -> new SwampDeadGrassBlock());
	public static final RegistryObject<Block> SWAMP_SAND_LAYER_1 = REGISTRY.register("swamp_sand_layer_1", () -> new SwampSandLayer1Block());
	public static final RegistryObject<Block> SWAMP_SAND_LAYER_2 = REGISTRY.register("swamp_sand_layer_2", () -> new SwampSandLayer2Block());
	public static final RegistryObject<Block> SAND_OF_MISSING_LAYER_1 = REGISTRY.register("sand_of_missing_layer_1", () -> new SandOfMissingLayer1Block());
	public static final RegistryObject<Block> SAND_OF_MISSING_LAYER_2 = REGISTRY.register("sand_of_missing_layer_2", () -> new SandOfMissingLayer2Block());
	public static final RegistryObject<Block> WASTER_FLOWER = REGISTRY.register("waster_flower", () -> new WasterFlowerBlock());
	public static final RegistryObject<Block> SWAMP_CLAY = REGISTRY.register("swamp_clay", () -> new SwampClayBlock());
	public static final RegistryObject<Block> PRISMARINE_CORAL_COLOURLESS = REGISTRY.register("prismarine_coral_colourless", () -> new PrismarineCoralColourlessBlock());
	public static final RegistryObject<Block> PRISMARINE_CORAL_FLASHING = REGISTRY.register("prismarine_coral_flashing", () -> new PrismarineCoralFlashingBlock());
	public static final RegistryObject<Block> PRISMARINE_CORAL_WAVE = REGISTRY.register("prismarine_coral_wave", () -> new PrismarineCoralWaveBlock());
	public static final RegistryObject<Block> PRISMARINE_CORAL_RICH = REGISTRY.register("prismarine_coral_rich", () -> new PrismarineCoralRichBlock());
	public static final RegistryObject<Block> GLOW_FUNGUS_WART = REGISTRY.register("glow_fungus_wart", () -> new LightFungusBlockBlock());
	public static final RegistryObject<Block> PRISMARINE_CORAL_DARKNESS = REGISTRY.register("prismarine_coral_darkness", () -> new PrismarineCoralDarknessBlock());
	public static final RegistryObject<Block> DEAD_PRISMARINE_CORAL_COLOURLESS = REGISTRY.register("dead_prismarine_coral_colourless", () -> new DeadPrismarineCoralColourlessBlock());
	public static final RegistryObject<Block> DEAD_PRISMARINE_CORAL_FLASHING = REGISTRY.register("dead_prismarine_coral_flashing", () -> new DeadPrismarineCoralFlashingBlock());
	public static final RegistryObject<Block> DEAD_PRISMARINE_CORAL_WAVE = REGISTRY.register("dead_prismarine_coral_wave", () -> new DeadPrismarineCoralWaveBlock());
	public static final RegistryObject<Block> DEAD_PRISMARINE_CORAL_RICH = REGISTRY.register("dead_prismarine_coral_rich", () -> new DeadPrismarineCoralRichBlock());
	public static final RegistryObject<Block> DEAD_PRISMARINE_CORAL_DARKNESS = REGISTRY.register("dead_prismarine_coral_darkness", () -> new DeadPrismarineCoralDarknessBlock());
	public static final RegistryObject<Block> PRISMARINUM_CORAL_COLOURLESS = REGISTRY.register("prismarinum_coral_colourless", () -> new PrismarinumCoralColourlessBlock());
	public static final RegistryObject<Block> PRISMARINUM_CORAL_FLASHING = REGISTRY.register("prismarinum_coral_flashing", () -> new PrismarinumCoralFlashingBlock());
	public static final RegistryObject<Block> PRISMARINUM_CORAL_WAVE = REGISTRY.register("prismarinum_coral_wave", () -> new PrismarinumCoralWaveBlock());
	public static final RegistryObject<Block> PRISMARINUM_CORAL_RICH = REGISTRY.register("prismarinum_coral_rich", () -> new PrismarinumCoralRichBlock());
	public static final RegistryObject<Block> PRISMARINUM_CORAL_DARKNESS = REGISTRY.register("prismarinum_coral_darkness", () -> new PrismarinumCoralDarknessBlock());
	public static final RegistryObject<Block> METENITE_GLASS = REGISTRY.register("metenite_glass", () -> new MeteniteGlassBlock());
	public static final RegistryObject<Block> METENITE_GLASS_PANE = REGISTRY.register("metenite_glass_pane", () -> new MeteniteGlassPaneBlock());
	public static final RegistryObject<Block> METENITE_BLOCK = REGISTRY.register("metenite_block", () -> new MeteniteBlockBlock());
	public static final RegistryObject<Block> RENTERIA_SAND = REGISTRY.register("renteria_sand", () -> new RenteriaSandBlock());
	public static final RegistryObject<Block> CRENRIT = REGISTRY.register("crenrit", () -> new CrenritBlock());
	public static final RegistryObject<Block> RECRA_GRASS = REGISTRY.register("recra_grass", () -> new RecraGrassBlock());
	public static final RegistryObject<Block> RECRA_FLOWER_1 = REGISTRY.register("recra_flower_1", () -> new RecraFlower1Block());
	public static final RegistryObject<Block> SWAMP_COBBLESTONE_STAIRS = REGISTRY.register("swamp_cobblestone_stairs", () -> new SwampCobblestoneStairsBlock());
	public static final RegistryObject<Block> SWAMP_COBBLESTONE_SLAB = REGISTRY.register("swamp_cobblestone_slab", () -> new SwampCobblestoneSlabBlock());
	public static final RegistryObject<Block> SWAMP_COBBLESTONE_WALL = REGISTRY.register("swamp_cobblestone_wall", () -> new SwampCobblestoneWallBlock());
	public static final RegistryObject<Block> ACCUSWAMP_MOSAIC = REGISTRY.register("accuswamp_mosaic", () -> new AccuswampMosaicBlock());
	public static final RegistryObject<Block> ACCUSWAMP_MOSAIC_STAIRS = REGISTRY.register("accuswamp_mosaic_stairs", () -> new AccuswampMosaicStairsBlock());
	public static final RegistryObject<Block> ACCUSWAMP_MOSAIC_SLAB = REGISTRY.register("accuswamp_mosaic_slab", () -> new AccuswampMosaicSlabBlock());
	public static final RegistryObject<Block> ACCUSWAMP_MOSAIC_WALL = REGISTRY.register("accuswamp_mosaic_wall", () -> new AccuswampMosaicWallBlock());
	public static final RegistryObject<Block> CRACKED_ACCUSWAMP_MOSAIC = REGISTRY.register("cracked_accuswamp_mosaic", () -> new CrackedAccuswampMosaicBlock());
	public static final RegistryObject<Block> CRACKED_ACCUSWAMP_MOSAIC_STAIRS = REGISTRY.register("cracked_accuswamp_mosaic_stairs", () -> new CrackedAccuswampMosaicStairsBlock());
	public static final RegistryObject<Block> CRACKED_ACCUSWAMP_MOSAIC_SLAB = REGISTRY.register("cracked_accuswamp_mosaic_slab", () -> new CrackedAccuswampMosaicSlabBlock());
	public static final RegistryObject<Block> CRACKED_ACCUSWAMP_MOSAIC_WALL = REGISTRY.register("cracked_accuswamp_mosaic_wall", () -> new CrackedAccuswampMosaicWallBlock());
	public static final RegistryObject<Block> LIGHT_MUSHROOMS_ACTIVE = REGISTRY.register("light_mushrooms_active", () -> new LightMushroomsActiveBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_STONE = REGISTRY.register("polished_swamp_stone", () -> new PolishedSwampStoneBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_STONE_STAIRS = REGISTRY.register("polished_swamp_stone_stairs", () -> new PolishedSwampStoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_STONE_SLAB = REGISTRY.register("polished_swamp_stone_slab", () -> new PolishedSwampStoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_STONE_WALL = REGISTRY.register("polished_swamp_stone_wall", () -> new PolishedSwampStoneWallBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_STONE_BRICKS = REGISTRY.register("polished_swamp_stone_bricks", () -> new PolishedSwampStoneBricksBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_STONE_BRICKS_STAIRS = REGISTRY.register("polished_swamp_stone_bricks_stairs", () -> new PolishedSwampStoneBricksStairsBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_STONE_BRICKS_SLAB = REGISTRY.register("polished_swamp_stone_bricks_slab", () -> new PolishedSwampStoneBricksSlabBlock());
	public static final RegistryObject<Block> POLISHED_SWAMP_STONE_BRICKS_WALL = REGISTRY.register("polished_swamp_stone_bricks_wall", () -> new PolishedSwampStoneBricksWallBlock());
	public static final RegistryObject<Block> CRACKED_POLISHED_SWAMP_STONE_BRICKS = REGISTRY.register("cracked_polished_swamp_stone_bricks", () -> new CrackedPolishedSwampStoneBricksBlock());
	public static final RegistryObject<Block> MOSSY_POLISHED_SWAMP_STONE_BRICKS = REGISTRY.register("mossy_polished_swamp_stone_bricks", () -> new MossyPolishedSwampStoneBricksBlock());
	public static final RegistryObject<Block> SWAMP_STONE_STAIRS = REGISTRY.register("swamp_stone_stairs", () -> new SwampStoneStairsBlock());
	public static final RegistryObject<Block> SWAMP_STONE_SLAB = REGISTRY.register("swamp_stone_slab", () -> new SwampStoneSlabBlock());
	public static final RegistryObject<Block> SWAMP_STONE_WALL = REGISTRY.register("swamp_stone_wall", () -> new SwampStoneWallBlock());
	public static final RegistryObject<Block> FAKE_WOOD = REGISTRY.register("fake_wood", () -> new FakeWoodBlock());
	public static final RegistryObject<Block> FAKE_LOG = REGISTRY.register("fake_log", () -> new FakeLogBlock());
	public static final RegistryObject<Block> FAKE_PLANKS = REGISTRY.register("fake_planks", () -> new FakePlanksBlock());
	public static final RegistryObject<Block> FAKE_LEAVES = REGISTRY.register("fake_leaves", () -> new FakeLeavesBlock());
	public static final RegistryObject<Block> FAKE_STAIRS = REGISTRY.register("fake_stairs", () -> new FakeStairsBlock());
	public static final RegistryObject<Block> FAKE_SLAB = REGISTRY.register("fake_slab", () -> new FakeSlabBlock());
	public static final RegistryObject<Block> FAKE_FENCE = REGISTRY.register("fake_fence", () -> new FakeFenceBlock());
	public static final RegistryObject<Block> FAKE_FENCE_GATE = REGISTRY.register("fake_fence_gate", () -> new FakeFenceGateBlock());
	public static final RegistryObject<Block> FAKE_PRESSURE_PLATE = REGISTRY.register("fake_pressure_plate", () -> new FakePressurePlateBlock());
	public static final RegistryObject<Block> FAKE_BUTTON = REGISTRY.register("fake_button", () -> new FakeButtonBlock());
	public static final RegistryObject<Block> STRIPPED_FAKE_WOOD = REGISTRY.register("stripped_fake_wood", () -> new StrippedFakeWoodBlock());
	public static final RegistryObject<Block> STRIPPED_FAKE_LOG = REGISTRY.register("stripped_fake_log", () -> new StrippedFakeLogBlock());
	public static final RegistryObject<Block> FAKE_DOOR = REGISTRY.register("fake_door", () -> new FakeDoorBlock());
	public static final RegistryObject<Block> FAKE_TRAP_DOOR = REGISTRY.register("fake_trap_door", () -> new FakeTrapDoorBlock());
	public static final RegistryObject<Block> SHADDY_MELON = REGISTRY.register("shaddy_melon", () -> new ShaddyMelonBlock());
	public static final RegistryObject<Block> FANTAL_BLOCK = REGISTRY.register("fantal_block", () -> new SoulstealBlockBlock());
	public static final RegistryObject<Block> FANTAL_GRID = REGISTRY.register("fantal_grid", () -> new SoulstealGridBlock());
	public static final RegistryObject<Block> LIGHT_OF_SOUL = REGISTRY.register("light_of_soul", () -> new LightOfSoulBlock());
	public static final RegistryObject<Block> CORRUPTED_BUBBLE_BLOCK = REGISTRY.register("corrupted_bubble_block", () -> new CorruptedBubbleBlockBlock());
	public static final RegistryObject<Block> CORRUPTED_SLIME = REGISTRY.register("corrupted_slime", () -> new CorruptedSlimeBlock());
	public static final RegistryObject<Block> GLOW_WOOD = REGISTRY.register("glow_wood", () -> new GlowWoodBlock());
	public static final RegistryObject<Block> GLOW_LOG = REGISTRY.register("glow_log", () -> new GlowLogBlock());
	public static final RegistryObject<Block> GLOW_PLANKS = REGISTRY.register("glow_planks", () -> new GlowPlanksBlock());
	public static final RegistryObject<Block> GLOW_STAIRS = REGISTRY.register("glow_stairs", () -> new GlowStairsBlock());
	public static final RegistryObject<Block> GLOW_SLAB = REGISTRY.register("glow_slab", () -> new GlowSlabBlock());
	public static final RegistryObject<Block> GLOW_FENCE = REGISTRY.register("glow_fence", () -> new GlowFenceBlock());
	public static final RegistryObject<Block> GLOW_FENCE_GATE = REGISTRY.register("glow_fence_gate", () -> new GlowFenceGateBlock());
	public static final RegistryObject<Block> GLOW_PRESSURE_PLATE = REGISTRY.register("glow_pressure_plate", () -> new GlowPressurePlateBlock());
	public static final RegistryObject<Block> GLOW_BUTTON = REGISTRY.register("glow_button", () -> new GlowButtonBlock());
	public static final RegistryObject<Block> GLOW_DOOR = REGISTRY.register("glow_door", () -> new GlowDoorBlock());
	public static final RegistryObject<Block> GLOW_TRAP_DOOR = REGISTRY.register("glow_trap_door", () -> new GlowTrapDoorBlock());
	public static final RegistryObject<Block> CORRUPTED_BUBBLE_EMPTY = REGISTRY.register("corrupted_bubble_empty", () -> new CorruptedBubbleEmptyBlock());
	public static final RegistryObject<Block> GLOW_VINE = REGISTRY.register("glow_vine", () -> new SporeVine2Block());
	public static final RegistryObject<Block> GLOW_FUNGUS_HAT_0 = REGISTRY.register("glow_fungus_hat_0", () -> new GlowFungusHatBlock());
	public static final RegistryObject<Block> DUST_CLAY = REGISTRY.register("dust_clay", () -> new DustClayBlock());
	public static final RegistryObject<Block> DUST_CLAY_STAIRS = REGISTRY.register("dust_clay_stairs", () -> new DustClayStairsBlock());
	public static final RegistryObject<Block> DUST_CLAY_SLAB = REGISTRY.register("dust_clay_slab", () -> new DustClaySlabBlock());
	public static final RegistryObject<Block> DUST_CLAY_WALL = REGISTRY.register("dust_clay_wall", () -> new DustClayWallBlock());
	public static final RegistryObject<Block> DUST_CLAY_BRICKS = REGISTRY.register("dust_clay_bricks", () -> new DustClayBricksBlock());
	public static final RegistryObject<Block> DUST_CLAY_BRICKS_STAIRS = REGISTRY.register("dust_clay_bricks_stairs", () -> new DustClayBricksStairsBlock());
	public static final RegistryObject<Block> DUST_CLAY_BRICKS_SLAB = REGISTRY.register("dust_clay_bricks_slab", () -> new DustClayBricksSlabBlock());
	public static final RegistryObject<Block> DUST_CLAY_BRICKS_WALL = REGISTRY.register("dust_clay_bricks_wall", () -> new DustClayBricksWallBlock());
	public static final RegistryObject<Block> GLOWNITE_GRID_LANTERN = REGISTRY.register("glownite_grid_lantern", () -> new GlowniteGridLanternBlock());
	public static final RegistryObject<Block> WASTELAND_BUSH = REGISTRY.register("wasteland_bush", () -> new WastelandBushBlock());
	public static final RegistryObject<Block> WASTELAND_SHEAF = REGISTRY.register("wasteland_sheaf", () -> new WastelandSheafBlock());
	public static final RegistryObject<Block> WASTELAND_SHEAF_STAIRS = REGISTRY.register("wasteland_sheaf_stairs", () -> new WastelandSheafStairsBlock());
	public static final RegistryObject<Block> WASTELAND_SHEAF_SLAB = REGISTRY.register("wasteland_sheaf_slab", () -> new WastelandSheafSlabBlock());
	public static final RegistryObject<Block> WASTELAND_SHEAF_FENCE = REGISTRY.register("wasteland_sheaf_fence", () -> new WastelandSheafFenceBlock());
	public static final RegistryObject<Block> GLOWNITE_BLOCK = REGISTRY.register("glownite_block", () -> new GlowniteBlockBlock());
	public static final RegistryObject<Block> GLOWNITE_STAIRS = REGISTRY.register("glownite_stairs", () -> new GlowniteStairsBlock());
	public static final RegistryObject<Block> GLOWNITE_SLAB = REGISTRY.register("glownite_slab", () -> new GlowniteSlabBlock());
	public static final RegistryObject<Block> CHISELED_GLOWNITE = REGISTRY.register("chiseled_glownite", () -> new ChiseledGlowniteBlock());
	public static final RegistryObject<Block> CHISELED_GLOWNITE_STAIRS = REGISTRY.register("chiseled_glownite_stairs", () -> new ChiseledGlowniteStairsBlock());
	public static final RegistryObject<Block> CHISELED_GLOWNITE_SLAB = REGISTRY.register("chiseled_glownite_slab", () -> new ChiseledGlowniteSlabBlock());
	public static final RegistryObject<Block> GLOWNITE_BRICKS = REGISTRY.register("glownite_bricks", () -> new GlowniteBricksBlock());
	public static final RegistryObject<Block> GLOWNITE_BRICKS_STAIRS = REGISTRY.register("glownite_bricks_stairs", () -> new GlowniteBricksStairsBlock());
	public static final RegistryObject<Block> GLOWNITE_BRICKS_SLAB = REGISTRY.register("glownite_bricks_slab", () -> new GlowniteBricksSlabBlock());
	public static final RegistryObject<Block> BIG_GLOWNITE_BRICKS = REGISTRY.register("big_glownite_bricks", () -> new BigGlowniteBricksBlock());
	public static final RegistryObject<Block> BIG_GLOWNITE_BRICKS_STAIRS = REGISTRY.register("big_glownite_bricks_stairs", () -> new BigGlowniteBricksStairsBlock());
	public static final RegistryObject<Block> BIG_GLOWNITE_BRICKS_SLAB = REGISTRY.register("big_glownite_bricks_slab", () -> new BigGlowniteBricksSlabBlock());
	public static final RegistryObject<Block> GLOWNITE_GRID = REGISTRY.register("glownite_grid", () -> new GlowniteGridBlock());
	public static final RegistryObject<Block> GLOWNITE_GRID_PANE = REGISTRY.register("glownite_grid_pane", () -> new GlowniteGridPaneBlock());
	public static final RegistryObject<Block> GLOWNITE_DOOR = REGISTRY.register("glownite_door", () -> new GlowniteDoorBlock());
	public static final RegistryObject<Block> GLOWNITE_TRAP_DOOR = REGISTRY.register("glownite_trap_door", () -> new GlowniteTrapDoorBlock());
	public static final RegistryObject<Block> BUBBLE = REGISTRY.register("bubble", () -> new BubbleBlock());
	public static final RegistryObject<Block> CVETALIY_CLUSTER = REGISTRY.register("cvetaliy_cluster", () -> new CvetaliyClusterBlock());
	public static final RegistryObject<Block> SUSPICIOUS_RENTERIA_SAND = REGISTRY.register("suspicious_renteria_sand", () -> new SuspiciousRenteriaSandBlock());
	public static final RegistryObject<Block> UNCLEAR_RENTERIA_SAND = REGISTRY.register("unclear_renteria_sand", () -> new UnclearRenteriaSandBlock());
	public static final RegistryObject<Block> CORRUPT_1 = REGISTRY.register("corrupt_1", () -> new Corrupt1Block());
	public static final RegistryObject<Block> CORRUPT_0 = REGISTRY.register("corrupt_0", () -> new Corrupt0Block());
	public static final RegistryObject<Block> CORRUPTED_ROOTS = REGISTRY.register("corrupted_roots", () -> new CorruptedRootsBlock());
	public static final RegistryObject<Block> BLINK_MUSHROOM_HAT = REGISTRY.register("blink_mushroom_hat", () -> new BlinkMushroomHatBlock());
	public static final RegistryObject<Block> SWAMP_STAR_GRASS = REGISTRY.register("swamp_star_grass", () -> new SwampStarGrassBlock());
	public static final RegistryObject<Block> BLINK_ROOTS = REGISTRY.register("blink_roots", () -> new BlinkRootsBlock());
	public static final RegistryObject<Block> ECHO_MASTER = REGISTRY.register("echo_master", () -> new EchoMasterBlock());
	public static final RegistryObject<Block> ECHO_FRUIT = REGISTRY.register("echo_fruit", () -> new FakeBoxBlock());
	public static final RegistryObject<Block> SMALL_SKULL = REGISTRY.register("small_skull", () -> new SmallSkullBlock());
	public static final RegistryObject<Block> CORRUPTED_REACTOR = REGISTRY.register("corrupted_reactor", () -> new CorruptedReactorBlock());
	public static final RegistryObject<Block> SEEKER_PLANT = REGISTRY.register("seeker_plant", () -> new SeekerPlantBlock());
	public static final RegistryObject<Block> SEEKER_PLANT_TOP = REGISTRY.register("seeker_plant_top", () -> new SeekerPlantTopBlock());
	public static final RegistryObject<Block> SEEKER_PLANT_GLOW = REGISTRY.register("seeker_plant_glow", () -> new SeekerPlantGlowBlock());
	public static final RegistryObject<Block> SEEKER_PLANT_GLOW_TOP = REGISTRY.register("seeker_plant_glow_top", () -> new SeekerPlantGlowTopBlock());
	public static final RegistryObject<Block> STRIPPED_GLOW_WOOD = REGISTRY.register("stripped_glow_wood", () -> new StrippedGlowWoodBlock());
	public static final RegistryObject<Block> STRIPPED_GLOW_LOG = REGISTRY.register("stripped_glow_log", () -> new StrippedGlowLogBlock());
	public static final RegistryObject<Block> CORRUPT_BRICKS = REGISTRY.register("corrupt_bricks", () -> new CorruptBricksBlock());
	public static final RegistryObject<Block> CORRUPT_BRICKS_STAIRS = REGISTRY.register("corrupt_bricks_stairs", () -> new CorruptBricksStairsBlock());
	public static final RegistryObject<Block> CORRUPT_BRICKS_SLAB = REGISTRY.register("corrupt_bricks_slab", () -> new CorruptBricksSlabBlock());
	public static final RegistryObject<Block> CORRUPT_BRICKS_WALL = REGISTRY.register("corrupt_bricks_wall", () -> new CorruptBricksWallBlock());
	public static final RegistryObject<Block> CHISELED_CORRUPT_BRICKS = REGISTRY.register("chiseled_corrupt_bricks", () -> new ChiseledCorruptedBricksBlock());
	public static final RegistryObject<Block> ICE_TEST_BLOCK = REGISTRY.register("ice_test_block", () -> new IceTestBlockBlock());
	public static final RegistryObject<Block> JUMP_TEST_BLOCK = REGISTRY.register("jump_test_block", () -> new JumpTestBlockBlock());
	public static final RegistryObject<Block> IGNIME_ORE = REGISTRY.register("ignime_ore", () -> new IgnimeOreBlock());
	public static final RegistryObject<Block> SAND_OF_MISSING_IRON_ORE = REGISTRY.register("sand_of_missing_iron_ore", () -> new SandOfMissingIronOreBlock());
	public static final RegistryObject<Block> UNDESKY_BLACKSOIL = REGISTRY.register("undesky_blacksoil", () -> new UndeskyBlacksoilBlock());
	public static final RegistryObject<Block> COBBLED_ACCUSTONE = REGISTRY.register("cobbled_accustone", () -> new CobbledAccustoneBlock());
	public static final RegistryObject<Block> COBBLED_ACCUSTONE_STAIRS = REGISTRY.register("cobbled_accustone_stairs", () -> new CobbledAccustoneStairsBlock());
	public static final RegistryObject<Block> COBBLED_ACCUSTONE_SLAB = REGISTRY.register("cobbled_accustone_slab", () -> new CobbledAccustoneSlabBlock());
	public static final RegistryObject<Block> COBBLED_ACCUSTONE_WALL = REGISTRY.register("cobbled_accustone_wall", () -> new CobbledAccustoneWallBlock());
	public static final RegistryObject<Block> NEASKY_WOOD = REGISTRY.register("neasky_wood", () -> new NeaskyWoodBlock());
	public static final RegistryObject<Block> NEASKY_LOG = REGISTRY.register("neasky_log", () -> new NeaskyLogBlock());
	public static final RegistryObject<Block> NEASKY_PLANKS = REGISTRY.register("neasky_planks", () -> new NeaskyPlanksBlock());
	public static final RegistryObject<Block> NEASKY_LEAVES = REGISTRY.register("neasky_leaves", () -> new NeaskyLeavesBlock());
	public static final RegistryObject<Block> NEASKY_STAIRS = REGISTRY.register("neasky_stairs", () -> new NeaskyStairsBlock());
	public static final RegistryObject<Block> NEASKY_SLAB = REGISTRY.register("neasky_slab", () -> new NeaskySlabBlock());
	public static final RegistryObject<Block> NEASKY_FENCE = REGISTRY.register("neasky_fence", () -> new NeaskyFenceBlock());
	public static final RegistryObject<Block> NEASKY_FENCE_GATE = REGISTRY.register("neasky_fence_gate", () -> new NeaskyFenceGateBlock());
	public static final RegistryObject<Block> NEASKY_PRESSURE_PLATE = REGISTRY.register("neasky_pressure_plate", () -> new NeaskyPressurePlateBlock());
	public static final RegistryObject<Block> NEASKY_BUTTON = REGISTRY.register("neasky_button", () -> new NeaskyButtonBlock());
	public static final RegistryObject<Block> SKYSTAR_GRASS = REGISTRY.register("skystar_grass", () -> new SkystarGrassBlock());
	public static final RegistryObject<Block> SKYSTAR_ROOTS = REGISTRY.register("skystar_roots", () -> new SkystarRootsBlock());
	public static final RegistryObject<Block> SKYSTAR_FERN = REGISTRY.register("skystar_fern", () -> new SkystarFernBlock());
	public static final RegistryObject<Block> SKYSTAR_FLOWERS = REGISTRY.register("skystar_flowers", () -> new SkystarFlowersBlock());
	public static final RegistryObject<Block> SKYSTAR_LARGE_FERN = REGISTRY.register("skystar_large_fern", () -> new SkystarLargeFernBlock());
	public static final RegistryObject<Block> UNCLEAR_DEEPSLATE_SAND = REGISTRY.register("unclear_deepslate_sand", () -> new UnclearDeepslateSandBlock());
	public static final RegistryObject<Block> NEASKY_PUMPKIN = REGISTRY.register("neasky_pumpkin", () -> new NeaskyPumpkinBlock());
	public static final RegistryObject<Block> STRIPPED_NEASKY_LOG = REGISTRY.register("stripped_neasky_log", () -> new StrippedNeaskyLogBlock());
	public static final RegistryObject<Block> STRIPPED_NEASKY_WOOD = REGISTRY.register("stripped_neasky_wood", () -> new StrippedNeaskyWoodBlock());
	public static final RegistryObject<Block> NEASKY_DOOR = REGISTRY.register("neasky_door", () -> new NeaskyDoorBlock());
	public static final RegistryObject<Block> NEASKY_TRAP_DOOR = REGISTRY.register("neasky_trap_door", () -> new NeaskyTrapDoorBlock());
	public static final RegistryObject<Block> CORRUPTED_GRASS_BLOCK = REGISTRY.register("corrupted_grass_block", () -> new CorruptedGrassBlockBlock());
	public static final RegistryObject<Block> CORRUPTED_LEAVES = REGISTRY.register("corrupted_leaves", () -> new CorruptyLeavesBlock());
	public static final RegistryObject<Block> BLOOMING_CORRUPTED_LEAVES = REGISTRY.register("blooming_corrupted_leaves", () -> new CorruptyLeavesFlowerBlock());
	public static final RegistryObject<Block> CORRUPTY_ROOTS = REGISTRY.register("corrupty_roots", () -> new CorruptyRootsBlock());
	public static final RegistryObject<Block> CORRUPTY_ROOTS_SMALL = REGISTRY.register("corrupty_roots_small", () -> new CorruptyRootsSmallBlock());
	public static final RegistryObject<Block> CORRUPTED_BUSH = REGISTRY.register("corrupted_bush", () -> new CorruptedBushBlock());
	public static final RegistryObject<Block> CORRUPTED_SCULK_CATALYST_BLOOMING = REGISTRY.register("corrupted_sculk_catalyst_blooming", () -> new CorruptedSculkCatalystBloomingBlock());
	public static final RegistryObject<Block> CORRUPTED_KNIGHT_REMNANTS = REGISTRY.register("corrupted_knight_remnants", () -> new CorruptedKnightRemnantsBlock());
	public static final RegistryObject<Block> ERIDIUM_CLUSTER = REGISTRY.register("eridium_cluster", () -> new EridiumClusterBlock());
	public static final RegistryObject<Block> CURSED_FURNACE = REGISTRY.register("cursed_furnace", () -> new CursedFurnaceBlock());
	public static final RegistryObject<Block> BLOOD_CONTAINER = REGISTRY.register("blood_container", () -> new BloodContainerBlock());
	public static final RegistryObject<Block> CURSED_PIPE = REGISTRY.register("cursed_pipe", () -> new CursedPipeBlock());
	public static final RegistryObject<Block> NEASKY_MOSS = REGISTRY.register("neasky_moss", () -> new MeaskyMossBlock());
	public static final RegistryObject<Block> MEASKY_CARPET = REGISTRY.register("measky_carpet", () -> new MeaskyCarpetBlock());
	public static final RegistryObject<Block> SKYSTAR_SMALL_ROOTS = REGISTRY.register("skystar_small_roots", () -> new SkystarSmallRootsBlock());
	public static final RegistryObject<Block> NEASKY_VINES = REGISTRY.register("neasky_vines", () -> new NeaskyVinesBlock());
	public static final RegistryObject<Block> METENITE_CLUSTER = REGISTRY.register("metenite_cluster", () -> new MeteniteClusterBlock());
	public static final RegistryObject<Block> MEASKY_LEAVES = REGISTRY.register("measky_leaves", () -> new MeaskyLeavesBlock());
	public static final RegistryObject<Block> DEAD_GRASS = REGISTRY.register("dead_grass", () -> new DeadGrassBlock());
	public static final RegistryObject<Block> STAR_TELEPORTER = REGISTRY.register("star_teleporter", () -> new StarTeleporterBlock());
	public static final RegistryObject<Block> CURSED_WORKBENCH = REGISTRY.register("cursed_workbench", () -> new CursedWorkbenchBlock());
	public static final RegistryObject<Block> CURSED_BOOKSHELF = REGISTRY.register("cursed_bookshelf", () -> new CursedBookshelfBlock());
	public static final RegistryObject<Block> CURSED_CAULDRON = REGISTRY.register("cursed_cauldron", () -> new CursedCauldronBlock());
	public static final RegistryObject<Block> CURSED_ANVIL = REGISTRY.register("cursed_anvil", () -> new CursedAnvilBlock());
	public static final RegistryObject<Block> CORRUPTED_LIGHT = REGISTRY.register("corrupted_light", () -> new CorruptedLightBlock());
	public static final RegistryObject<Block> PURULENT_SPRUCE_LOG = REGISTRY.register("purulent_spruce_log", () -> new PurulentSpruceLogBlock());
	public static final RegistryObject<Block> SCULK_SOIL = REGISTRY.register("sculk_soil", () -> new SculkSoilBlock());
	public static final RegistryObject<Block> CURSED_SCALE = REGISTRY.register("cursed_scale", () -> new CursedScaleBlock());
	public static final RegistryObject<Block> CRYING_WOOD = REGISTRY.register("crying_wood", () -> new CryingWoodBlock());
	public static final RegistryObject<Block> CRYING_LOG = REGISTRY.register("crying_log", () -> new CryingLogBlock());
	public static final RegistryObject<Block> STRIPPED_CRYING_WOOD = REGISTRY.register("stripped_crying_wood", () -> new StrippedCryingWoodBlock());
	public static final RegistryObject<Block> STRIPPED_CRYING_LOG = REGISTRY.register("stripped_crying_log", () -> new StrippedCryingLogBlock());
	public static final RegistryObject<Block> CORRUPTED_LANTERN = REGISTRY.register("corrupted_lantern", () -> new CorruptedLanternBlock());
	public static final RegistryObject<Block> CORRUPTED_CAMPFIRE = REGISTRY.register("corrupted_campfire", () -> new CorruptedCampfireBlock());
	public static final RegistryObject<Block> SKYFALL_ORE = REGISTRY.register("skyfall_ore", () -> new SkyfallOreBlock());
	public static final RegistryObject<Block> MOSSY_CORRUPTED_BRICKS = REGISTRY.register("mossy_corrupted_bricks", () -> new MossyCorruptedBricksBlock());
	public static final RegistryObject<Block> CORRUPTED_VINES_2 = REGISTRY.register("corrupted_vines_2", () -> new CorruptedVines2Block());
	public static final RegistryObject<Block> CORRUPTED_SOIL = REGISTRY.register("corrupted_soil", () -> new CorruptedSoilBlock());
	public static final RegistryObject<Block> CRYING_LEAVES = REGISTRY.register("crying_leaves", () -> new CryingLeavesBlock());
	public static final RegistryObject<Block> BLOOMING_CRYING_LAEVES = REGISTRY.register("blooming_crying_laeves", () -> new BloomingCryingLaevesBlock());
	public static final RegistryObject<Block> POISONER = REGISTRY.register("poisoner", () -> new PoisonerBlock());
	public static final RegistryObject<Block> MEASKY_TREE = REGISTRY.register("measky_tree", () -> new MeaskyTreeBlock());
	public static final RegistryObject<Block> CURSED_LECTERN = REGISTRY.register("cursed_lectern", () -> new CursedLecternBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
