
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package exp.fluffynuar.truedarkness.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import exp.fluffynuar.truedarkness.item.WaterFlaskItem;
import exp.fluffynuar.truedarkness.item.WastelandWheatItem;
import exp.fluffynuar.truedarkness.item.UnknownDrinkItem;
import exp.fluffynuar.truedarkness.item.UnknownDrinkFlaskItem;
import exp.fluffynuar.truedarkness.item.TrudniteItem;
import exp.fluffynuar.truedarkness.item.TrudniteIngotItem;
import exp.fluffynuar.truedarkness.item.ToolFangItem;
import exp.fluffynuar.truedarkness.item.SweetHerbsItem;
import exp.fluffynuar.truedarkness.item.SwampSlimyItem;
import exp.fluffynuar.truedarkness.item.SwampSeaweedItemItem;
import exp.fluffynuar.truedarkness.item.SwampPollenItem;
import exp.fluffynuar.truedarkness.item.SwampPlantsSalatItem;
import exp.fluffynuar.truedarkness.item.SwampMirrorItem;
import exp.fluffynuar.truedarkness.item.SwampKelpItemItem;
import exp.fluffynuar.truedarkness.item.SwampCodItem;
import exp.fluffynuar.truedarkness.item.SwampAmuletItem;
import exp.fluffynuar.truedarkness.item.StoneSpoolItem;
import exp.fluffynuar.truedarkness.item.StoneMetalItem;
import exp.fluffynuar.truedarkness.item.StoneHeartItem;
import exp.fluffynuar.truedarkness.item.SporeVineItemItem;
import exp.fluffynuar.truedarkness.item.SoulstealWingsItem;
import exp.fluffynuar.truedarkness.item.SoulstealSwordItem;
import exp.fluffynuar.truedarkness.item.SoulstealSmithingTemplateItem;
import exp.fluffynuar.truedarkness.item.SoulstealShovelItem;
import exp.fluffynuar.truedarkness.item.SoulstealShardItem;
import exp.fluffynuar.truedarkness.item.SoulstealPickaxeItem;
import exp.fluffynuar.truedarkness.item.SoulstealNuggetItem;
import exp.fluffynuar.truedarkness.item.SoulstealKnifeItem;
import exp.fluffynuar.truedarkness.item.SoulstealIngotItem;
import exp.fluffynuar.truedarkness.item.SoulstealHoeItem;
import exp.fluffynuar.truedarkness.item.SoulstealHeartItem;
import exp.fluffynuar.truedarkness.item.SoulstealHammerItem;
import exp.fluffynuar.truedarkness.item.SoulstealAxeItem;
import exp.fluffynuar.truedarkness.item.SoulWingsItem;
import exp.fluffynuar.truedarkness.item.SoulStoneItem;
import exp.fluffynuar.truedarkness.item.SoulSpoolItem;
import exp.fluffynuar.truedarkness.item.SoulItem;
import exp.fluffynuar.truedarkness.item.SoulGrainItem;
import exp.fluffynuar.truedarkness.item.SoulCrystalItem;
import exp.fluffynuar.truedarkness.item.SoulBottleItem;
import exp.fluffynuar.truedarkness.item.SoothingHerbsItem;
import exp.fluffynuar.truedarkness.item.SmokedSlicedStemItem;
import exp.fluffynuar.truedarkness.item.SmallPoorSlimeItem;
import exp.fluffynuar.truedarkness.item.SlicedStemItem;
import exp.fluffynuar.truedarkness.item.SkulkedSwordItem;
import exp.fluffynuar.truedarkness.item.SkulkedShovelItem;
import exp.fluffynuar.truedarkness.item.SkulkedPickaxeItem;
import exp.fluffynuar.truedarkness.item.SkulkedHoeItem;
import exp.fluffynuar.truedarkness.item.SkulkedAxeItem;
import exp.fluffynuar.truedarkness.item.SkrezhalItem;
import exp.fluffynuar.truedarkness.item.SieveItem;
import exp.fluffynuar.truedarkness.item.ShandarahItem;
import exp.fluffynuar.truedarkness.item.ShaddyMelonItemItem;
import exp.fluffynuar.truedarkness.item.SeaHeartAmuletItem;
import exp.fluffynuar.truedarkness.item.SculkRingItem;
import exp.fluffynuar.truedarkness.item.SculkRing1Item;
import exp.fluffynuar.truedarkness.item.SculkManaBottleItem;
import exp.fluffynuar.truedarkness.item.SculkFeatherItem;
import exp.fluffynuar.truedarkness.item.ScilkedAppleItem;
import exp.fluffynuar.truedarkness.item.SandglassItem;
import exp.fluffynuar.truedarkness.item.SandRemnantsItem;
import exp.fluffynuar.truedarkness.item.ReelItem;
import exp.fluffynuar.truedarkness.item.RealGeneralSwordItem;
import exp.fluffynuar.truedarkness.item.RawTrudniteItem;
import exp.fluffynuar.truedarkness.item.RawFireniteItem;
import exp.fluffynuar.truedarkness.item.PotholdersItem;
import exp.fluffynuar.truedarkness.item.PoorSlimeItem;
import exp.fluffynuar.truedarkness.item.PollenFeatherItem;
import exp.fluffynuar.truedarkness.item.PhotoItem;
import exp.fluffynuar.truedarkness.item.PhasmaSwordItem;
import exp.fluffynuar.truedarkness.item.OceanSkrezhalPartItem;
import exp.fluffynuar.truedarkness.item.MusicDiscTurquoiseFlowerItem;
import exp.fluffynuar.truedarkness.item.MusicDiscRainItem;
import exp.fluffynuar.truedarkness.item.MusicDiscLapisItem;
import exp.fluffynuar.truedarkness.item.MusicDiscHumilityItem;
import exp.fluffynuar.truedarkness.item.MusicDiscHollowItem;
import exp.fluffynuar.truedarkness.item.MusicDiscForestNightItem;
import exp.fluffynuar.truedarkness.item.MushroomHatItem;
import exp.fluffynuar.truedarkness.item.MeteniteShardItem;
import exp.fluffynuar.truedarkness.item.MeteniteIngotItem;
import exp.fluffynuar.truedarkness.item.MeteniteCrystalItem;
import exp.fluffynuar.truedarkness.item.MeteniteArmorItem;
import exp.fluffynuar.truedarkness.item.MedicinalHerbsItem;
import exp.fluffynuar.truedarkness.item.LightedBerryItem;
import exp.fluffynuar.truedarkness.item.LightShroomItemItem;
import exp.fluffynuar.truedarkness.item.LetterItem;
import exp.fluffynuar.truedarkness.item.LavenderTeaItem;
import exp.fluffynuar.truedarkness.item.LavenderTeaFlaskItem;
import exp.fluffynuar.truedarkness.item.LavenderPetalItem;
import exp.fluffynuar.truedarkness.item.JugPatternItem;
import exp.fluffynuar.truedarkness.item.IcebergAmuletItem;
import exp.fluffynuar.truedarkness.item.HeartEridiumItem;
import exp.fluffynuar.truedarkness.item.GrimniteItem;
import exp.fluffynuar.truedarkness.item.GrapeItem;
import exp.fluffynuar.truedarkness.item.GramiteStickItem;
import exp.fluffynuar.truedarkness.item.GramiteShovelItem;
import exp.fluffynuar.truedarkness.item.GramiteShardItem;
import exp.fluffynuar.truedarkness.item.GramitePickaxeItem;
import exp.fluffynuar.truedarkness.item.GramiteHoeItem;
import exp.fluffynuar.truedarkness.item.GramiteDaggerItem;
import exp.fluffynuar.truedarkness.item.GramiteBattleAxeItem;
import exp.fluffynuar.truedarkness.item.GlowniteIngotItem;
import exp.fluffynuar.truedarkness.item.GlowFungusHatItemItem;
import exp.fluffynuar.truedarkness.item.GlowBerryJamItem;
import exp.fluffynuar.truedarkness.item.GlassBottleCorruptItem;
import exp.fluffynuar.truedarkness.item.GeneralWingsItem;
import exp.fluffynuar.truedarkness.item.GeneralScaleItem;
import exp.fluffynuar.truedarkness.item.GeneralRegulationItem;
import exp.fluffynuar.truedarkness.item.GeneralMirrorItem;
import exp.fluffynuar.truedarkness.item.GeneralKnifeItem;
import exp.fluffynuar.truedarkness.item.GeneralHeartItem;
import exp.fluffynuar.truedarkness.item.GeneralArmorItem;
import exp.fluffynuar.truedarkness.item.FruitsAndBerriesItem;
import exp.fluffynuar.truedarkness.item.FruitTeaItem;
import exp.fluffynuar.truedarkness.item.FruitTeaFlaskItem;
import exp.fluffynuar.truedarkness.item.FrozenStealKeyItem;
import exp.fluffynuar.truedarkness.item.ForeignRootsItem;
import exp.fluffynuar.truedarkness.item.FlaskItem;
import exp.fluffynuar.truedarkness.item.FireniteSwordItem;
import exp.fluffynuar.truedarkness.item.FireniteShovelItem;
import exp.fluffynuar.truedarkness.item.FireniteScrapItem;
import exp.fluffynuar.truedarkness.item.FirenitePickaxeItem;
import exp.fluffynuar.truedarkness.item.FireniteIngotItem;
import exp.fluffynuar.truedarkness.item.FireniteHoeItem;
import exp.fluffynuar.truedarkness.item.FireniteAxeItem;
import exp.fluffynuar.truedarkness.item.FireniteArmorItem;
import exp.fluffynuar.truedarkness.item.FirefliesbottleItem;
import exp.fluffynuar.truedarkness.item.FangPickaxeItem;
import exp.fluffynuar.truedarkness.item.EridiumShardItem;
import exp.fluffynuar.truedarkness.item.EridiumMirrorItem;
import exp.fluffynuar.truedarkness.item.EridiumHeartItem;
import exp.fluffynuar.truedarkness.item.EridiumBoneItem;
import exp.fluffynuar.truedarkness.item.EncoriteShardItem;
import exp.fluffynuar.truedarkness.item.EmptyTreasureAmuletItem;
import exp.fluffynuar.truedarkness.item.EmptyChiseledGlassShardItem;
import exp.fluffynuar.truedarkness.item.EmptyChiseledAncientGlassShardItem;
import exp.fluffynuar.truedarkness.item.ElderTearItem;
import exp.fluffynuar.truedarkness.item.ElderDocumentItem;
import exp.fluffynuar.truedarkness.item.EchoWingsItem;
import exp.fluffynuar.truedarkness.item.EchoStoneItem;
import exp.fluffynuar.truedarkness.item.EchoSpoolItem;
import exp.fluffynuar.truedarkness.item.EchoPapyrusItem;
import exp.fluffynuar.truedarkness.item.EchoKnifeItem;
import exp.fluffynuar.truedarkness.item.EchoHeartItem;
import exp.fluffynuar.truedarkness.item.EchoHarpItem;
import exp.fluffynuar.truedarkness.item.EchoHammerItem;
import exp.fluffynuar.truedarkness.item.EchoFeatherItem;
import exp.fluffynuar.truedarkness.item.DrinkRecipeItem;
import exp.fluffynuar.truedarkness.item.DriedSwampKelpItem;
import exp.fluffynuar.truedarkness.item.DistabilizatorItem;
import exp.fluffynuar.truedarkness.item.DisorientDustItem;
import exp.fluffynuar.truedarkness.item.DarknessSpruceShieldItem;
import exp.fluffynuar.truedarkness.item.DarkCrystalSwordItem;
import exp.fluffynuar.truedarkness.item.DarkCrystalShovelItem;
import exp.fluffynuar.truedarkness.item.DarkCrystalPickaxeItem;
import exp.fluffynuar.truedarkness.item.DarkCrystalHoeItem;
import exp.fluffynuar.truedarkness.item.DarkCrystalClasterItem;
import exp.fluffynuar.truedarkness.item.DarkCrystalAxeItem;
import exp.fluffynuar.truedarkness.item.CvetaliyItem;
import exp.fluffynuar.truedarkness.item.CvetaliyGrainItem;
import exp.fluffynuar.truedarkness.item.CvetaliyCrownItem;
import exp.fluffynuar.truedarkness.item.CvetalitShardItem;
import exp.fluffynuar.truedarkness.item.CursedSwordItem;
import exp.fluffynuar.truedarkness.item.CursedPapyrusItem;
import exp.fluffynuar.truedarkness.item.CursedMetalItem;
import exp.fluffynuar.truedarkness.item.CursedBattleAxeItem;
import exp.fluffynuar.truedarkness.item.CupWaterItem;
import exp.fluffynuar.truedarkness.item.CupItem;
import exp.fluffynuar.truedarkness.item.CryerPlasmItem;
import exp.fluffynuar.truedarkness.item.CryPickaxeItem;
import exp.fluffynuar.truedarkness.item.CryIngotItem;
import exp.fluffynuar.truedarkness.item.CryHammerItem;
import exp.fluffynuar.truedarkness.item.CrushedBluberriesItem;
import exp.fluffynuar.truedarkness.item.CrownItem;
import exp.fluffynuar.truedarkness.item.CrackedTreasureAmuletItem;
import exp.fluffynuar.truedarkness.item.CorruptedItem;
import exp.fluffynuar.truedarkness.item.CorruptedHandFangsItem;
import exp.fluffynuar.truedarkness.item.CorruptedFireniteSwordItem;
import exp.fluffynuar.truedarkness.item.CorruptedAxeItem;
import exp.fluffynuar.truedarkness.item.CorruptedAmuletItem;
import exp.fluffynuar.truedarkness.item.CoralAmuletItem;
import exp.fluffynuar.truedarkness.item.CoffeeItem;
import exp.fluffynuar.truedarkness.item.CoffeeFlaskItem;
import exp.fluffynuar.truedarkness.item.CocoaItem;
import exp.fluffynuar.truedarkness.item.ChiseledGlassShardItem;
import exp.fluffynuar.truedarkness.item.ChiseledGlassShard4Item;
import exp.fluffynuar.truedarkness.item.ChiseledGlassShard3Item;
import exp.fluffynuar.truedarkness.item.ChiseledGlassShard2Item;
import exp.fluffynuar.truedarkness.item.ChiseledGlassShard1Item;
import exp.fluffynuar.truedarkness.item.ChiseledAncientGlassShardItem;
import exp.fluffynuar.truedarkness.item.ChargeFeatherItem;
import exp.fluffynuar.truedarkness.item.CaveSkrezhalPartItem;
import exp.fluffynuar.truedarkness.item.CalmAquamarineItem;
import exp.fluffynuar.truedarkness.item.BubbleRodItem;
import exp.fluffynuar.truedarkness.item.BluederryJuiceItem;
import exp.fluffynuar.truedarkness.item.BlueberryJuiceFlaskItem;
import exp.fluffynuar.truedarkness.item.BlueberryItem;
import exp.fluffynuar.truedarkness.item.BerrySaladItem;
import exp.fluffynuar.truedarkness.item.AquaticItem;
import exp.fluffynuar.truedarkness.item.AquaticAmuletItem;
import exp.fluffynuar.truedarkness.item.AquamarineMirrorItem;
import exp.fluffynuar.truedarkness.item.AquamarineCoinItem;
import exp.fluffynuar.truedarkness.item.AncientRegulationItem;
import exp.fluffynuar.truedarkness.item.AncientPapyrusItem;
import exp.fluffynuar.truedarkness.item.AncientMirrorWillItem;
import exp.fluffynuar.truedarkness.item.AncientMirrorReinforceItem;
import exp.fluffynuar.truedarkness.item.AncientMirrorItem;
import exp.fluffynuar.truedarkness.item.AccustonePebblesItem;
import exp.fluffynuar.truedarkness.TruedarknessMod;

public class TruedarknessModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, TruedarknessMod.MODID);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_WOOD = block(TruedarknessModBlocks.DARKNESS_SPRUCE_WOOD);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_LOG = block(TruedarknessModBlocks.DARKNESS_SPRUCE_LOG);
	public static final RegistryObject<Item> STRIPPED_DARKNESS_SPRUCE = block(TruedarknessModBlocks.STRIPPED_DARKNESS_SPRUCE);
	public static final RegistryObject<Item> STRIPPED_DARKNESS_SPRUCE_LOG = block(TruedarknessModBlocks.STRIPPED_DARKNESS_SPRUCE_LOG);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_BOX = block(TruedarknessModBlocks.DARKNESS_SPRUCE_BOX);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_PLANKS = block(TruedarknessModBlocks.DARKNESS_SPRUCE_PLANKS);
	public static final RegistryObject<Item> MOSSY_DARKNESS_SPRUCE_PLANKS = block(TruedarknessModBlocks.MOSSY_DARKNESS_SPRUCE_PLANKS);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_LEAVES = block(TruedarknessModBlocks.DARKNESS_SPRUCE_LEAVES);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_STAIRS = block(TruedarknessModBlocks.DARKNESS_SPRUCE_STAIRS);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_SLAB = block(TruedarknessModBlocks.DARKNESS_SPRUCE_SLAB);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_FENCE = block(TruedarknessModBlocks.DARKNESS_SPRUCE_FENCE);
	public static final RegistryObject<Item> CYAN = block(TruedarknessModBlocks.CYAN);
	public static final RegistryObject<Item> CYAN_STEM = block(TruedarknessModBlocks.CYAN_STEM);
	public static final RegistryObject<Item> STRIPPED_CYAN_WOOD = block(TruedarknessModBlocks.STRIPPED_CYAN_WOOD);
	public static final RegistryObject<Item> STRIPPED_CYAN_LOG = block(TruedarknessModBlocks.STRIPPED_CYAN_LOG);
	public static final RegistryObject<Item> CYAN_PLANKS = block(TruedarknessModBlocks.CYAN_PLANKS);
	public static final RegistryObject<Item> CYAN_PETAL = block(TruedarknessModBlocks.CYAN_PETAL);
	public static final RegistryObject<Item> CYAN_BOOKSHELF = block(TruedarknessModBlocks.CYAN_BOOKSHELF);
	public static final RegistryObject<Item> CYAN_STAIRS = block(TruedarknessModBlocks.CYAN_STAIRS);
	public static final RegistryObject<Item> CYAN_SLAB = block(TruedarknessModBlocks.CYAN_SLAB);
	public static final RegistryObject<Item> CYAN_FENCE = block(TruedarknessModBlocks.CYAN_FENCE);
	public static final RegistryObject<Item> FAKE_WOOD = block(TruedarknessModBlocks.FAKE_WOOD);
	public static final RegistryObject<Item> FAKE_LOG = block(TruedarknessModBlocks.FAKE_LOG);
	public static final RegistryObject<Item> STRIPPED_FAKE_WOOD = block(TruedarknessModBlocks.STRIPPED_FAKE_WOOD);
	public static final RegistryObject<Item> STRIPPED_FAKE_LOG = block(TruedarknessModBlocks.STRIPPED_FAKE_LOG);
	public static final RegistryObject<Item> FAKE_PLANKS = block(TruedarknessModBlocks.FAKE_PLANKS);
	public static final RegistryObject<Item> FAKE_LEAVES = block(TruedarknessModBlocks.FAKE_LEAVES);
	public static final RegistryObject<Item> FAKE_STAIRS = block(TruedarknessModBlocks.FAKE_STAIRS);
	public static final RegistryObject<Item> FAKE_SLAB = block(TruedarknessModBlocks.FAKE_SLAB);
	public static final RegistryObject<Item> FAKE_FENCE = block(TruedarknessModBlocks.FAKE_FENCE);
	public static final RegistryObject<Item> MYCELIUM_WOOD = block(TruedarknessModBlocks.MYCELIUM_WOOD);
	public static final RegistryObject<Item> MYCELIUM_LOG = block(TruedarknessModBlocks.MYCELIUM_LOG);
	public static final RegistryObject<Item> STRIPPED_MYCELIUM_WOOD = block(TruedarknessModBlocks.STRIPPED_MYCELIUM_WOOD);
	public static final RegistryObject<Item> STRIPPED_MYCELIUM_LOG = block(TruedarknessModBlocks.STRIPPED_MYCELIUM_LOG);
	public static final RegistryObject<Item> MYCELIUM_PLANKS = block(TruedarknessModBlocks.MYCELIUM_PLANKS);
	public static final RegistryObject<Item> MYCELIUM_STAIRS = block(TruedarknessModBlocks.MYCELIUM_STAIRS);
	public static final RegistryObject<Item> MYCELIUM_SLAB = block(TruedarknessModBlocks.MYCELIUM_SLAB);
	public static final RegistryObject<Item> MYCELIUM_FENCE = block(TruedarknessModBlocks.MYCELIUM_FENCE);
	public static final RegistryObject<Item> GLOW_WOOD = block(TruedarknessModBlocks.GLOW_WOOD);
	public static final RegistryObject<Item> GLOW_LOG = block(TruedarknessModBlocks.GLOW_LOG);
	public static final RegistryObject<Item> GLOW_PLANKS = block(TruedarknessModBlocks.GLOW_PLANKS);
	public static final RegistryObject<Item> GLOW_FUNGUS_WART = block(TruedarknessModBlocks.GLOW_FUNGUS_WART);
	public static final RegistryObject<Item> GLOW_STAIRS = block(TruedarknessModBlocks.GLOW_STAIRS);
	public static final RegistryObject<Item> GLOW_SLAB = block(TruedarknessModBlocks.GLOW_SLAB);
	public static final RegistryObject<Item> GLOW_FENCE = block(TruedarknessModBlocks.GLOW_FENCE);
	public static final RegistryObject<Item> CRYING_PLANKS = block(TruedarknessModBlocks.CRYING_PLANKS);
	public static final RegistryObject<Item> CRYING_STAIRS = block(TruedarknessModBlocks.CRYING_STAIRS);
	public static final RegistryObject<Item> CRYING_SLAB = block(TruedarknessModBlocks.CRYING_SLAB);
	public static final RegistryObject<Item> CRYING_FENCE = block(TruedarknessModBlocks.CRYING_FENCE);
	public static final RegistryObject<Item> DRIED_WOOD = block(TruedarknessModBlocks.DRIED_WOOD);
	public static final RegistryObject<Item> DRIED_LOG = block(TruedarknessModBlocks.DRIED_LOG);
	public static final RegistryObject<Item> DRIED_PLANKS = block(TruedarknessModBlocks.DRIED_PLANKS);
	public static final RegistryObject<Item> DRIED_STAIRS = block(TruedarknessModBlocks.DRIED_STAIRS);
	public static final RegistryObject<Item> DRIED_SLAB = block(TruedarknessModBlocks.DRIED_SLAB);
	public static final RegistryObject<Item> DRIED_FENCE = block(TruedarknessModBlocks.DRIED_FENCE);
	public static final RegistryObject<Item> SWAMP_COBBLESTONE = block(TruedarknessModBlocks.SWAMP_COBBLESTONE);
	public static final RegistryObject<Item> SWAMP_COBBLESTONE_STAIRS = block(TruedarknessModBlocks.SWAMP_COBBLESTONE_STAIRS);
	public static final RegistryObject<Item> SWAMP_COBBLESTONE_SLAB = block(TruedarknessModBlocks.SWAMP_COBBLESTONE_SLAB);
	public static final RegistryObject<Item> SWAMP_COBBLESTONE_WALL = block(TruedarknessModBlocks.SWAMP_COBBLESTONE_WALL);
	public static final RegistryObject<Item> POLISHED_SWAMP_COBBLESTONE = block(TruedarknessModBlocks.POLISHED_SWAMP_COBBLESTONE);
	public static final RegistryObject<Item> POLISHED_SWAMP_COBBLESTONE_STAIRS = block(TruedarknessModBlocks.POLISHED_SWAMP_COBBLESTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_SWAMP_COBBLESTONE_SLAB = block(TruedarknessModBlocks.POLISHED_SWAMP_COBBLESTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_SWAMP_COBBLESTONE_WALL = block(TruedarknessModBlocks.POLISHED_SWAMP_COBBLESTONE_WALL);
	public static final RegistryObject<Item> SWAMP_BRICKS = block(TruedarknessModBlocks.SWAMP_BRICKS);
	public static final RegistryObject<Item> CHISELED_SWAMP_BRICKS = block(TruedarknessModBlocks.CHISELED_SWAMP_BRICKS);
	public static final RegistryObject<Item> MOSSY_SWAMP_BRICKS = block(TruedarknessModBlocks.MOSSY_SWAMP_BRICKS);
	public static final RegistryObject<Item> CRACKED_SWAMP_BRICKS = block(TruedarknessModBlocks.CRACKED_SWAMP_BRICKS);
	public static final RegistryObject<Item> SWAMP_BRICKS_STAIRS = block(TruedarknessModBlocks.SWAMP_BRICKS_STAIRS);
	public static final RegistryObject<Item> SWAMP_BRICKS_SLAB = block(TruedarknessModBlocks.SWAMP_BRICKS_SLAB);
	public static final RegistryObject<Item> SWAMP_BRICKS_WALL = block(TruedarknessModBlocks.SWAMP_BRICKS_WALL);
	public static final RegistryObject<Item> SWAMP_STONE = block(TruedarknessModBlocks.SWAMP_STONE);
	public static final RegistryObject<Item> SWAMP_STONE_STAIRS = block(TruedarknessModBlocks.SWAMP_STONE_STAIRS);
	public static final RegistryObject<Item> SWAMP_STONE_SLAB = block(TruedarknessModBlocks.SWAMP_STONE_SLAB);
	public static final RegistryObject<Item> SWAMP_STONE_WALL = block(TruedarknessModBlocks.SWAMP_STONE_WALL);
	public static final RegistryObject<Item> POLISHED_SWAMP_STONE = block(TruedarknessModBlocks.POLISHED_SWAMP_STONE);
	public static final RegistryObject<Item> POLISHED_SWAMP_STONE_STAIRS = block(TruedarknessModBlocks.POLISHED_SWAMP_STONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_SWAMP_STONE_SLAB = block(TruedarknessModBlocks.POLISHED_SWAMP_STONE_SLAB);
	public static final RegistryObject<Item> POLISHED_SWAMP_STONE_WALL = block(TruedarknessModBlocks.POLISHED_SWAMP_STONE_WALL);
	public static final RegistryObject<Item> POLISHED_SWAMP_STONE_BRICKS = block(TruedarknessModBlocks.POLISHED_SWAMP_STONE_BRICKS);
	public static final RegistryObject<Item> CHISELED_POLISHED_SWAMP_STONE_BRICKS = block(TruedarknessModBlocks.CHISELED_POLISHED_SWAMP_STONE_BRICKS);
	public static final RegistryObject<Item> CRACKED_POLISHED_SWAMP_STONE_BRICKS = block(TruedarknessModBlocks.CRACKED_POLISHED_SWAMP_STONE_BRICKS);
	public static final RegistryObject<Item> MOSSY_POLISHED_SWAMP_STONE_BRICKS = block(TruedarknessModBlocks.MOSSY_POLISHED_SWAMP_STONE_BRICKS);
	public static final RegistryObject<Item> POLISHED_SWAMP_STONE_BRICKS_STAIRS = block(TruedarknessModBlocks.POLISHED_SWAMP_STONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> POLISHED_SWAMP_STONE_BRICKS_SLAB = block(TruedarknessModBlocks.POLISHED_SWAMP_STONE_BRICKS_SLAB);
	public static final RegistryObject<Item> POLISHED_SWAMP_STONE_BRICKS_WALL = block(TruedarknessModBlocks.POLISHED_SWAMP_STONE_BRICKS_WALL);
	public static final RegistryObject<Item> TRUDNITE_ORE = block(TruedarknessModBlocks.TRUDNITE_ORE);
	public static final RegistryObject<Item> LAPIS_LAZULI_SWAMP_ORE = block(TruedarknessModBlocks.LAPIS_LAZULI_SWAMP_ORE);
	public static final RegistryObject<Item> SWAMP_SLIMY_ORE = block(TruedarknessModBlocks.SWAMP_SLIMY_ORE);
	public static final RegistryObject<Item> CVETALIY_ORE = block(TruedarknessModBlocks.CVETALIY_ORE);
	public static final RegistryObject<Item> SWAMP_SAND = block(TruedarknessModBlocks.SWAMP_SAND);
	public static final RegistryObject<Item> SWAMP_TERRACOTA = block(TruedarknessModBlocks.SWAMP_TERRACOTA);
	public static final RegistryObject<Item> POLISHED_ACCUSTONE = block(TruedarknessModBlocks.POLISHED_ACCUSTONE);
	public static final RegistryObject<Item> POLISHED_ACCUSTONE_STAIRS = block(TruedarknessModBlocks.POLISHED_ACCUSTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_ACCUSTONE_SLAB = block(TruedarknessModBlocks.POLISHED_ACCUSTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_ACCUSTONE_WALL = block(TruedarknessModBlocks.POLISHED_ACCUSTONE_WALL);
	public static final RegistryObject<Item> POLISHED_ACCUSTONE_BRICKS = block(TruedarknessModBlocks.POLISHED_ACCUSTONE_BRICKS);
	public static final RegistryObject<Item> CRACKED_POLISHED_ACCUSTONE_BRICKS = block(TruedarknessModBlocks.CRACKED_POLISHED_ACCUSTONE_BRICKS);
	public static final RegistryObject<Item> CHISELED_POLISHED_ACCUSTONE_BRICKS = block(TruedarknessModBlocks.CHISELED_POLISHED_ACCUSTONE_BRICKS);
	public static final RegistryObject<Item> MOSSY_POLISHED_ACCUSTONE_BRICKS = block(TruedarknessModBlocks.MOSSY_POLISHED_ACCUSTONE_BRICKS);
	public static final RegistryObject<Item> POLISHED_ACCUSTONE_BRICKS_STAIRS = block(TruedarknessModBlocks.POLISHED_ACCUSTONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> POLISHED_ACCUSTONE_BRICKS_SLAB = block(TruedarknessModBlocks.POLISHED_ACCUSTONE_BRICKS_SLAB);
	public static final RegistryObject<Item> POLISHED_ACCUSTONE_BRICKS_WALL = block(TruedarknessModBlocks.POLISHED_ACCUSTONE_BRICKS_WALL);
	public static final RegistryObject<Item> ACCUSWAMP_MOSAIC = block(TruedarknessModBlocks.ACCUSWAMP_MOSAIC);
	public static final RegistryObject<Item> CRACKED_ACCUSWAMP_MOSAIC = block(TruedarknessModBlocks.CRACKED_ACCUSWAMP_MOSAIC);
	public static final RegistryObject<Item> ACCUSWAMP_MOSAIC_STAIRS = block(TruedarknessModBlocks.ACCUSWAMP_MOSAIC_STAIRS);
	public static final RegistryObject<Item> CRACKED_ACCUSWAMP_MOSAIC_STAIRS = block(TruedarknessModBlocks.CRACKED_ACCUSWAMP_MOSAIC_STAIRS);
	public static final RegistryObject<Item> ACCUSWAMP_MOSAIC_SLAB = block(TruedarknessModBlocks.ACCUSWAMP_MOSAIC_SLAB);
	public static final RegistryObject<Item> CRACKED_ACCUSWAMP_MOSAIC_SLAB = block(TruedarknessModBlocks.CRACKED_ACCUSWAMP_MOSAIC_SLAB);
	public static final RegistryObject<Item> ACCUSWAMP_MOSAIC_WALL = block(TruedarknessModBlocks.ACCUSWAMP_MOSAIC_WALL);
	public static final RegistryObject<Item> CRACKED_ACCUSWAMP_MOSAIC_WALL = block(TruedarknessModBlocks.CRACKED_ACCUSWAMP_MOSAIC_WALL);
	public static final RegistryObject<Item> SWAMP_CLAY = block(TruedarknessModBlocks.SWAMP_CLAY);
	public static final RegistryObject<Item> SWAMP_MUD = block(TruedarknessModBlocks.SWAMP_MUD);
	public static final RegistryObject<Item> DUST_BLOCK = block(TruedarknessModBlocks.DUST_BLOCK);
	public static final RegistryObject<Item> DUST_CLAY = block(TruedarknessModBlocks.DUST_CLAY);
	public static final RegistryObject<Item> DUST_CLAY_STAIRS = block(TruedarknessModBlocks.DUST_CLAY_STAIRS);
	public static final RegistryObject<Item> DUST_CLAY_SLAB = block(TruedarknessModBlocks.DUST_CLAY_SLAB);
	public static final RegistryObject<Item> DUST_CLAY_WALL = block(TruedarknessModBlocks.DUST_CLAY_WALL);
	public static final RegistryObject<Item> DUST_CLAY_BRICKS = block(TruedarknessModBlocks.DUST_CLAY_BRICKS);
	public static final RegistryObject<Item> DUST_CLAY_BRICKS_STAIRS = block(TruedarknessModBlocks.DUST_CLAY_BRICKS_STAIRS);
	public static final RegistryObject<Item> DUST_CLAY_BRICKS_SLAB = block(TruedarknessModBlocks.DUST_CLAY_BRICKS_SLAB);
	public static final RegistryObject<Item> DUST_CLAY_BRICKS_WALL = block(TruedarknessModBlocks.DUST_CLAY_BRICKS_WALL);
	public static final RegistryObject<Item> SAND_OF_MISSING = block(TruedarknessModBlocks.SAND_OF_MISSING);
	public static final RegistryObject<Item> SANDSTONE_OF_MISSING = block(TruedarknessModBlocks.SANDSTONE_OF_MISSING);
	public static final RegistryObject<Item> SANDSTONE_OF_MISSING_STAIRS = block(TruedarknessModBlocks.SANDSTONE_OF_MISSING_STAIRS);
	public static final RegistryObject<Item> SANDSTONE_OF_MISSING_SLAB = block(TruedarknessModBlocks.SANDSTONE_OF_MISSING_SLAB);
	public static final RegistryObject<Item> SANDSTONE_OF_MISSING_WALL = block(TruedarknessModBlocks.SANDSTONE_OF_MISSING_WALL);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_OF_MISSING = block(TruedarknessModBlocks.POLISHED_SANDSTONE_OF_MISSING);
	public static final RegistryObject<Item> CHISELED_POLISHED_SANDSTONE_OF_MISSING_1 = block(TruedarknessModBlocks.CHISELED_POLISHED_SANDSTONE_OF_MISSING_1);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_OF_MISSING_STAIRS = block(TruedarknessModBlocks.POLISHED_SANDSTONE_OF_MISSING_STAIRS);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_OF_MISSING_SLAB = block(TruedarknessModBlocks.POLISHED_SANDSTONE_OF_MISSING_SLAB);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_OF_MISSING_WALL = block(TruedarknessModBlocks.POLISHED_SANDSTONE_OF_MISSING_WALL);
	public static final RegistryObject<Item> CHISELED_POLISHED_SANDSTONE_OF_MISSING_2 = block(TruedarknessModBlocks.CHISELED_POLISHED_SANDSTONE_OF_MISSING_2);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_OF_MISSING_STAIRS_1 = block(TruedarknessModBlocks.POLISHED_SANDSTONE_OF_MISSING_STAIRS_1);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_OF_MISSING_SLAB_1 = block(TruedarknessModBlocks.POLISHED_SANDSTONE_OF_MISSING_SLAB_1);
	public static final RegistryObject<Item> CHISELED_POLISHED_SANDSTONE_OF_MISSING = block(TruedarknessModBlocks.CHISELED_POLISHED_SANDSTONE_OF_MISSING);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_BRICKS_OF_MISSING = block(TruedarknessModBlocks.POLISHED_SANDSTONE_BRICKS_OF_MISSING);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_BRICKS_OF_MISSING_PILLAR = block(TruedarknessModBlocks.POLISHED_SANDSTONE_BRICKS_OF_MISSING_PILLAR);
	public static final RegistryObject<Item> BUSHED_POLISHED_SANDSTONE_BRICKS_OF_MISSING = block(TruedarknessModBlocks.BUSHED_POLISHED_SANDSTONE_BRICKS_OF_MISSING);
	public static final RegistryObject<Item> CRACKED_SANDSTONE_BRICKS_OF_MISSING = block(TruedarknessModBlocks.CRACKED_SANDSTONE_BRICKS_OF_MISSING);
	public static final RegistryObject<Item> CHISELED_POLISHED_SANDSTONE_BRICKS_OF_MISSING = block(TruedarknessModBlocks.CHISELED_POLISHED_SANDSTONE_BRICKS_OF_MISSING);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_BRICKS_OF_MISSING_STAIRS = block(TruedarknessModBlocks.POLISHED_SANDSTONE_BRICKS_OF_MISSING_STAIRS);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_BRICKS_OF_MISSING_SLAB = block(TruedarknessModBlocks.POLISHED_SANDSTONE_BRICKS_OF_MISSING_SLAB);
	public static final RegistryObject<Item> POLISHED_SANDSTONE_BRICKS_OF_MISSING_WALL = block(TruedarknessModBlocks.POLISHED_SANDSTONE_BRICKS_OF_MISSING_WALL);
	public static final RegistryObject<Item> TRAP_SAND_OF_MISSING = block(TruedarknessModBlocks.TRAP_SAND_OF_MISSING);
	public static final RegistryObject<Item> UNCLEAR_SAND_OF_MISSING = block(TruedarknessModBlocks.UNCLEAR_SAND_OF_MISSING);
	public static final RegistryObject<Item> DRIED_SWAMP_BUSH = block(TruedarknessModBlocks.DRIED_SWAMP_BUSH);
	public static final RegistryObject<Item> DEAD_BUSH_SWAMP = block(TruedarknessModBlocks.DEAD_BUSH_SWAMP);
	public static final RegistryObject<Item> SWAMP_DEAD_GRASS = block(TruedarknessModBlocks.SWAMP_DEAD_GRASS);
	public static final RegistryObject<Item> WASTER_FLOWER = block(TruedarknessModBlocks.WASTER_FLOWER);
	public static final RegistryObject<Item> WASTELAND_BUSH = block(TruedarknessModBlocks.WASTELAND_BUSH);
	public static final RegistryObject<Item> WASTELAND_SHEAF = block(TruedarknessModBlocks.WASTELAND_SHEAF);
	public static final RegistryObject<Item> WASTELAND_SHEAF_STAIRS = block(TruedarknessModBlocks.WASTELAND_SHEAF_STAIRS);
	public static final RegistryObject<Item> WASTELAND_SHEAF_SLAB = block(TruedarknessModBlocks.WASTELAND_SHEAF_SLAB);
	public static final RegistryObject<Item> WASTELAND_SHEAF_FENCE = block(TruedarknessModBlocks.WASTELAND_SHEAF_FENCE);
	public static final RegistryObject<Item> DARKNITE = block(TruedarknessModBlocks.DARKNITE);
	public static final RegistryObject<Item> DARKNITE_STAIRS = block(TruedarknessModBlocks.DARKNITE_STAIRS);
	public static final RegistryObject<Item> DARKNITE_SLAB = block(TruedarknessModBlocks.DARKNITE_SLAB);
	public static final RegistryObject<Item> DARKNITE_WALL = block(TruedarknessModBlocks.DARKNITE_WALL);
	public static final RegistryObject<Item> COBBLED_DARKNITE = block(TruedarknessModBlocks.COBBLED_DARKNITE);
	public static final RegistryObject<Item> COBBLED_DARKNITE_STAIRS = block(TruedarknessModBlocks.COBBLED_DARKNITE_STAIRS);
	public static final RegistryObject<Item> COBBLED_DARKNITE_SLAB = block(TruedarknessModBlocks.COBBLED_DARKNITE_SLAB);
	public static final RegistryObject<Item> COBBLED_DARKNITE_WALL = block(TruedarknessModBlocks.COBBLED_DARKNITE_WALL);
	public static final RegistryObject<Item> DARKNITE_BRICKS = block(TruedarknessModBlocks.DARKNITE_BRICKS);
	public static final RegistryObject<Item> CRACKED_DARKNITE_BRICKS = block(TruedarknessModBlocks.CRACKED_DARKNITE_BRICKS);
	public static final RegistryObject<Item> CHISELED_DARKNITE_BRICKS = block(TruedarknessModBlocks.CHISELED_DARKNITE_BRICKS);
	public static final RegistryObject<Item> DARKNITE_BRICKS_STAIRS = block(TruedarknessModBlocks.DARKNITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> DARKNITE_BRICKS_SLAB = block(TruedarknessModBlocks.DARKNITE_BRICKS_SLAB);
	public static final RegistryObject<Item> DARKNITE_BRICKS_WALL = block(TruedarknessModBlocks.DARKNITE_BRICKS_WALL);
	public static final RegistryObject<Item> GRAMITE_ORE = block(TruedarknessModBlocks.GRAMITE_ORE);
	public static final RegistryObject<Item> GLOWNITE_BLOCK = block(TruedarknessModBlocks.GLOWNITE_BLOCK);
	public static final RegistryObject<Item> GLOWNITE_STAIRS = block(TruedarknessModBlocks.GLOWNITE_STAIRS);
	public static final RegistryObject<Item> GLOWNITE_SLAB = block(TruedarknessModBlocks.GLOWNITE_SLAB);
	public static final RegistryObject<Item> CHISELED_GLOWNITE = block(TruedarknessModBlocks.CHISELED_GLOWNITE);
	public static final RegistryObject<Item> CHISELED_GLOWNITE_STAIRS = block(TruedarknessModBlocks.CHISELED_GLOWNITE_STAIRS);
	public static final RegistryObject<Item> CHISELED_GLOWNITE_SLAB = block(TruedarknessModBlocks.CHISELED_GLOWNITE_SLAB);
	public static final RegistryObject<Item> GLOWNITE_DOOR = doubleBlock(TruedarknessModBlocks.GLOWNITE_DOOR);
	public static final RegistryObject<Item> GLOWNITE_GRID = block(TruedarknessModBlocks.GLOWNITE_GRID);
	public static final RegistryObject<Item> GLOWNITE_GRID_PANE = block(TruedarknessModBlocks.GLOWNITE_GRID_PANE);
	public static final RegistryObject<Item> GLOWNITE_TRAP_DOOR = block(TruedarknessModBlocks.GLOWNITE_TRAP_DOOR);
	public static final RegistryObject<Item> GLOWNITE_BRICKS = block(TruedarknessModBlocks.GLOWNITE_BRICKS);
	public static final RegistryObject<Item> GLOWNITE_BRICKS_STAIRS = block(TruedarknessModBlocks.GLOWNITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> GLOWNITE_BRICKS_SLAB = block(TruedarknessModBlocks.GLOWNITE_BRICKS_SLAB);
	public static final RegistryObject<Item> BIG_GLOWNITE_BRICKS = block(TruedarknessModBlocks.BIG_GLOWNITE_BRICKS);
	public static final RegistryObject<Item> BIG_GLOWNITE_BRICKS_STAIRS = block(TruedarknessModBlocks.BIG_GLOWNITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> BIG_GLOWNITE_BRICKS_SLAB = block(TruedarknessModBlocks.BIG_GLOWNITE_BRICKS_SLAB);
	public static final RegistryObject<Item> PRISMARINE_CORAL_COLOURLESS = block(TruedarknessModBlocks.PRISMARINE_CORAL_COLOURLESS);
	public static final RegistryObject<Item> DEAD_PRISMARINE_CORAL_COLOURLESS = block(TruedarknessModBlocks.DEAD_PRISMARINE_CORAL_COLOURLESS);
	public static final RegistryObject<Item> PRISMARINUM_CORAL_COLOURLESS = block(TruedarknessModBlocks.PRISMARINUM_CORAL_COLOURLESS);
	public static final RegistryObject<Item> PRISMARINE_CORAL_FLASHING = block(TruedarknessModBlocks.PRISMARINE_CORAL_FLASHING);
	public static final RegistryObject<Item> DEAD_PRISMARINE_CORAL_FLASHING = block(TruedarknessModBlocks.DEAD_PRISMARINE_CORAL_FLASHING);
	public static final RegistryObject<Item> PRISMARINUM_CORAL_FLASHING = block(TruedarknessModBlocks.PRISMARINUM_CORAL_FLASHING);
	public static final RegistryObject<Item> PRISMARINE_CORAL_WAVE = block(TruedarknessModBlocks.PRISMARINE_CORAL_WAVE);
	public static final RegistryObject<Item> DEAD_PRISMARINE_CORAL_WAVE = block(TruedarknessModBlocks.DEAD_PRISMARINE_CORAL_WAVE);
	public static final RegistryObject<Item> PRISMARINUM_CORAL_WAVE = block(TruedarknessModBlocks.PRISMARINUM_CORAL_WAVE);
	public static final RegistryObject<Item> PRISMARINE_CORAL_RICH = block(TruedarknessModBlocks.PRISMARINE_CORAL_RICH);
	public static final RegistryObject<Item> DEAD_PRISMARINE_CORAL_RICH = block(TruedarknessModBlocks.DEAD_PRISMARINE_CORAL_RICH);
	public static final RegistryObject<Item> PRISMARINUM_CORAL_RICH = block(TruedarknessModBlocks.PRISMARINUM_CORAL_RICH);
	public static final RegistryObject<Item> PRISMARINE_CORAL_DARKNESS = block(TruedarknessModBlocks.PRISMARINE_CORAL_DARKNESS);
	public static final RegistryObject<Item> DEAD_PRISMARINE_CORAL_DARKNESS = block(TruedarknessModBlocks.DEAD_PRISMARINE_CORAL_DARKNESS);
	public static final RegistryObject<Item> PRISMARINUM_CORAL_DARKNESS = block(TruedarknessModBlocks.PRISMARINUM_CORAL_DARKNESS);
	public static final RegistryObject<Item> BUBBLE = block(TruedarknessModBlocks.BUBBLE);
	public static final RegistryObject<Item> SWAMP_SEAWEED_ITEM = REGISTRY.register("swamp_seaweed_item", () -> new SwampSeaweedItemItem());
	public static final RegistryObject<Item> SWAMP_KELP_ITEM = REGISTRY.register("swamp_kelp_item", () -> new SwampKelpItemItem());
	public static final RegistryObject<Item> CORRUPT = block(TruedarknessModBlocks.CORRUPT);
	public static final RegistryObject<Item> CORRUPTED_SCULK = block(TruedarknessModBlocks.CORRUPTED_SCULK);
	public static final RegistryObject<Item> CORRUPTED_SCULK_CATALYST = block(TruedarknessModBlocks.CORRUPTED_SCULK_CATALYST);
	public static final RegistryObject<Item> CORRUPTED_BUBBLE_BLOCK = block(TruedarknessModBlocks.CORRUPTED_BUBBLE_BLOCK);
	public static final RegistryObject<Item> CORRUPTED_BUBBLE_EMPTY = block(TruedarknessModBlocks.CORRUPTED_BUBBLE_EMPTY);
	public static final RegistryObject<Item> CORRUPTED_SLIME = block(TruedarknessModBlocks.CORRUPTED_SLIME);
	public static final RegistryObject<Item> CORRUPTED_HUMAN_BLOCK = block(TruedarknessModBlocks.CORRUPTED_HUMAN_BLOCK);
	public static final RegistryObject<Item> CORRUPTED_SUNFLOWER = doubleBlock(TruedarknessModBlocks.CORRUPTED_SUNFLOWER);
	public static final RegistryObject<Item> CORRUPTED_FLOWER = block(TruedarknessModBlocks.CORRUPTED_FLOWER);
	public static final RegistryObject<Item> CORRUPTED_GRASS = block(TruedarknessModBlocks.CORRUPTED_GRASS);
	public static final RegistryObject<Item> CORRUPTED_LEAVES = block(TruedarknessModBlocks.CORRUPTED_LEAVES);
	public static final RegistryObject<Item> SWAMP_SOIL = block(TruedarknessModBlocks.SWAMP_SOIL);
	public static final RegistryObject<Item> MYCELIUM_GRASS = block(TruedarknessModBlocks.MYCELIUM_GRASS);
	public static final RegistryObject<Item> GLOW_FUNGUS_HAT_ITEM = REGISTRY.register("glow_fungus_hat_item", () -> new GlowFungusHatItemItem());
	public static final RegistryObject<Item> MYCELIUM_ROOTS = block(TruedarknessModBlocks.MYCELIUM_ROOTS);
	public static final RegistryObject<Item> LIGHT_MUSHROOMS_ACTIVE = block(TruedarknessModBlocks.LIGHT_MUSHROOMS_ACTIVE);
	public static final RegistryObject<Item> LIGHT_MUSHROOM_TALL = doubleBlock(TruedarknessModBlocks.LIGHT_MUSHROOM_TALL);
	public static final RegistryObject<Item> LIGHT_SHROOM_ITEM = REGISTRY.register("light_shroom_item", () -> new LightShroomItemItem());
	public static final RegistryObject<Item> SPORE_VINE = REGISTRY.register("spore_vine", () -> new SporeVineItemItem());
	public static final RegistryObject<Item> SWAMP_DIRT = block(TruedarknessModBlocks.SWAMP_DIRT);
	public static final RegistryObject<Item> SWAMP_BLACK_SOIL = block(TruedarknessModBlocks.SWAMP_BLACK_SOIL);
	public static final RegistryObject<Item> SWAMP_SUNFLOWER = doubleBlock(TruedarknessModBlocks.SWAMP_SUNFLOWER);
	public static final RegistryObject<Item> SWAMP_CATTAIL = doubleBlock(TruedarknessModBlocks.SWAMP_CATTAIL);
	public static final RegistryObject<Item> LIGHTED_BERRY = REGISTRY.register("lighted_berry", () -> new LightedBerryItem());
	public static final RegistryObject<Item> SWAMP_LILY = block(TruedarknessModBlocks.SWAMP_LILY);
	public static final RegistryObject<Item> SWAMP_CHAMOMILE = block(TruedarknessModBlocks.SWAMP_CHAMOMILE);
	public static final RegistryObject<Item> SWAMP_TALL_GRASS = block(TruedarknessModBlocks.SWAMP_TALL_GRASS);
	public static final RegistryObject<Item> SWAMP_GRASS = block(TruedarknessModBlocks.SWAMP_GRASS);
	public static final RegistryObject<Item> SWAMP_BUSH = block(TruedarknessModBlocks.SWAMP_BUSH);
	public static final RegistryObject<Item> SWAMP_BLACKSOIL_COVER = block(TruedarknessModBlocks.SWAMP_BLACKSOIL_COVER);
	public static final RegistryObject<Item> CRENRIT = block(TruedarknessModBlocks.CRENRIT);
	public static final RegistryObject<Item> RENTERIA_SAND = block(TruedarknessModBlocks.RENTERIA_SAND);
	public static final RegistryObject<Item> ANCIENT_SCULK = block(TruedarknessModBlocks.ANCIENT_SCULK);
	public static final RegistryObject<Item> SHADDY_MELON = block(TruedarknessModBlocks.SHADDY_MELON);
	public static final RegistryObject<Item> RECRA_FLOWER = block(TruedarknessModBlocks.RECRA_FLOWER);
	public static final RegistryObject<Item> RECRA_FLOWER_2 = block(TruedarknessModBlocks.RECRA_FLOWER_2);
	public static final RegistryObject<Item> RECRA_FLOWER_1 = block(TruedarknessModBlocks.RECRA_FLOWER_1);
	public static final RegistryObject<Item> RECRA_GRASS = block(TruedarknessModBlocks.RECRA_GRASS);
	public static final RegistryObject<Item> METENITE_GLASS = block(TruedarknessModBlocks.METENITE_GLASS);
	public static final RegistryObject<Item> METENITE_GLASS_PANE = block(TruedarknessModBlocks.METENITE_GLASS_PANE);
	public static final RegistryObject<Item> ERIDIUM_GLASS = block(TruedarknessModBlocks.ERIDIUM_GLASS);
	public static final RegistryObject<Item> ERIDIUM_GLASS_PANE = block(TruedarknessModBlocks.ERIDIUM_GLASS_PANE);
	public static final RegistryObject<Item> EMPTY_CHISELED_ANCIENT_GLASS = block(TruedarknessModBlocks.EMPTY_CHISELED_ANCIENT_GLASS);
	public static final RegistryObject<Item> EMPTY_CHISELED_ANCIENT_GLASS_PANE = block(TruedarknessModBlocks.EMPTY_CHISELED_ANCIENT_GLASS_PANE);
	public static final RegistryObject<Item> CHISELED_ANCIENT_GLASS = block(TruedarknessModBlocks.CHISELED_ANCIENT_GLASS);
	public static final RegistryObject<Item> CHISELED_ANCIENT_GLASS_PANE = block(TruedarknessModBlocks.CHISELED_ANCIENT_GLASS_PANE);
	public static final RegistryObject<Item> EMPTY_CHISELED_GLASS = block(TruedarknessModBlocks.EMPTY_CHISELED_GLASS);
	public static final RegistryObject<Item> EMPTY_CHISELED_GLASS_PANE = block(TruedarknessModBlocks.EMPTY_CHISELED_GLASS_PANE);
	public static final RegistryObject<Item> CHISELED_GLASS = block(TruedarknessModBlocks.CHISELED_GLASS);
	public static final RegistryObject<Item> CHISELED_GLASS_PANE = block(TruedarknessModBlocks.CHISELED_GLASS_PANE);
	public static final RegistryObject<Item> CHISELED_GLASS_1 = block(TruedarknessModBlocks.CHISELED_GLASS_1);
	public static final RegistryObject<Item> CHISELED_GLASS_PANE_1 = block(TruedarknessModBlocks.CHISELED_GLASS_PANE_1);
	public static final RegistryObject<Item> CHISELED_GLASS_2 = block(TruedarknessModBlocks.CHISELED_GLASS_2);
	public static final RegistryObject<Item> CHISELED_GLASS_PANE_2 = block(TruedarknessModBlocks.CHISELED_GLASS_PANE_2);
	public static final RegistryObject<Item> CHISELED_GLASS_3 = block(TruedarknessModBlocks.CHISELED_GLASS_3);
	public static final RegistryObject<Item> CHISELED_GLASS_PANE_3 = block(TruedarknessModBlocks.CHISELED_GLASS_PANE_3);
	public static final RegistryObject<Item> CHISELED_GLASS_4 = block(TruedarknessModBlocks.CHISELED_GLASS_4);
	public static final RegistryObject<Item> CHISELED_GLASS_PANE_4 = block(TruedarknessModBlocks.CHISELED_GLASS_PANE_4);
	public static final RegistryObject<Item> SOULSTEAL_GRID = block(TruedarknessModBlocks.SOULSTEAL_GRID);
	public static final RegistryObject<Item> LIGHT_OF_SOUL = block(TruedarknessModBlocks.LIGHT_OF_SOUL);
	public static final RegistryObject<Item> GLOWNITE_GRID_LANTERN = block(TruedarknessModBlocks.GLOWNITE_GRID_LANTERN);
	public static final RegistryObject<Item> BLACKSMITE_FORGE = block(TruedarknessModBlocks.BLACKSMITE_FORGE);
	public static final RegistryObject<Item> SAMOVAR = block(TruedarknessModBlocks.SAMOVAR);
	public static final RegistryObject<Item> KETTLE = block(TruedarknessModBlocks.KETTLE);
	public static final RegistryObject<Item> COPPER_KETTLE = block(TruedarknessModBlocks.COPPER_KETTLE);
	public static final RegistryObject<Item> WOODEN_MUG = block(TruedarknessModBlocks.WOODEN_MUG);
	public static final RegistryObject<Item> MINERS_POT = block(TruedarknessModBlocks.MINERS_POT);
	public static final RegistryObject<Item> BIG_BOOK = block(TruedarknessModBlocks.BIG_BOOK);
	public static final RegistryObject<Item> INKS = block(TruedarknessModBlocks.INKS);
	public static final RegistryObject<Item> TABLECLOTH = block(TruedarknessModBlocks.TABLECLOTH);
	public static final RegistryObject<Item> BAG = block(TruedarknessModBlocks.BAG);
	public static final RegistryObject<Item> GLASS_JAR = block(TruedarknessModBlocks.GLASS_JAR);
	public static final RegistryObject<Item> PROECTOR = block(TruedarknessModBlocks.PROECTOR);
	public static final RegistryObject<Item> SOUL_ANCHOR = block(TruedarknessModBlocks.SOUL_ANCHOR);
	public static final RegistryObject<Item> EMPTY_FIREFLIES_OAK_LOG = block(TruedarknessModBlocks.EMPTY_FIREFLIES_OAK_LOG);
	public static final RegistryObject<Item> FIREFLIES_OAK_LOG = block(TruedarknessModBlocks.FIREFLIES_OAK_LOG);
	public static final RegistryObject<Item> FIREFLIES_FLOWER = block(TruedarknessModBlocks.FIREFLIES_FLOWER);
	public static final RegistryObject<Item> LAVENDER = block(TruedarknessModBlocks.LAVENDER);
	public static final RegistryObject<Item> TALL_LAVENDER = doubleBlock(TruedarknessModBlocks.TALL_LAVENDER);
	public static final RegistryObject<Item> GRAPE_AZALEA_LEAVES = block(TruedarknessModBlocks.GRAPE_AZALEA_LEAVES);
	public static final RegistryObject<Item> BUSHY_GRAPE_AZALEA_LEAVES = block(TruedarknessModBlocks.BUSHY_GRAPE_AZALEA_LEAVES);
	public static final RegistryObject<Item> RUNED_SWAMP_STONE = block(TruedarknessModBlocks.RUNED_SWAMP_STONE);
	public static final RegistryObject<Item> CORRUPTED_RUNE = block(TruedarknessModBlocks.CORRUPTED_RUNE);
	public static final RegistryObject<Item> METENITE_CLUSTER = block(TruedarknessModBlocks.METENITE_CLUSTER);
	public static final RegistryObject<Item> ERIDIUM_CLUSTER = block(TruedarknessModBlocks.ERIDIUM_CLUSTER);
	public static final RegistryObject<Item> CVETALIY_CLUSTER = block(TruedarknessModBlocks.CVETALIY_CLUSTER);
	public static final RegistryObject<Item> METENITE = block(TruedarknessModBlocks.METENITE);
	public static final RegistryObject<Item> ERIDIUM = block(TruedarknessModBlocks.ERIDIUM);
	public static final RegistryObject<Item> CVETALIY_BLOCK = block(TruedarknessModBlocks.CVETALIY_BLOCK);
	public static final RegistryObject<Item> DARK_CRYSTAL_CLUSTER_BLOCK = block(TruedarknessModBlocks.DARK_CRYSTAL_CLUSTER_BLOCK);
	public static final RegistryObject<Item> GRAMITE_BLOCK = block(TruedarknessModBlocks.GRAMITE_BLOCK);
	public static final RegistryObject<Item> FIRENITE_BLOCK = block(TruedarknessModBlocks.FIRENITE_BLOCK);
	public static final RegistryObject<Item> SOULSTEAL_BLOCK = block(TruedarknessModBlocks.SOULSTEAL_BLOCK);
	public static final RegistryObject<Item> TRUDNITE_BLOCK = block(TruedarknessModBlocks.TRUDNITE_BLOCK);
	public static final RegistryObject<Item> CRY_BLOCK = block(TruedarknessModBlocks.CRY_BLOCK);
	public static final RegistryObject<Item> METENITE_BLOCK = block(TruedarknessModBlocks.METENITE_BLOCK);
	public static final RegistryObject<Item> ERIDIUM_BLOCK = block(TruedarknessModBlocks.ERIDIUM_BLOCK);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_CHEST = block(TruedarknessModBlocks.DARKNESS_SPRUCE_CHEST);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_FENCE_GATE = block(TruedarknessModBlocks.DARKNESS_SPRUCE_FENCE_GATE);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_DOOR = doubleBlock(TruedarknessModBlocks.DARKNESS_SPRUCE_DOOR);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_TRAP_DOOR = block(TruedarknessModBlocks.DARKNESS_SPRUCE_TRAP_DOOR);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_PRESSURE_PLATE = block(TruedarknessModBlocks.DARKNESS_SPRUCE_PRESSURE_PLATE);
	public static final RegistryObject<Item> DARKNESS_SPRUCE_BUTTON = block(TruedarknessModBlocks.DARKNESS_SPRUCE_BUTTON);
	public static final RegistryObject<Item> CYAN_FENCE_GATE = block(TruedarknessModBlocks.CYAN_FENCE_GATE);
	public static final RegistryObject<Item> CYAN_DOOR = doubleBlock(TruedarknessModBlocks.CYAN_DOOR);
	public static final RegistryObject<Item> CYAN_TRAP_DOOR = block(TruedarknessModBlocks.CYAN_TRAP_DOOR);
	public static final RegistryObject<Item> CYAN_PRESSURE_PLATE = block(TruedarknessModBlocks.CYAN_PRESSURE_PLATE);
	public static final RegistryObject<Item> CYAN_BUTTON = block(TruedarknessModBlocks.CYAN_BUTTON);
	public static final RegistryObject<Item> MYCELIUM_FENCE_GATE = block(TruedarknessModBlocks.MYCELIUM_FENCE_GATE);
	public static final RegistryObject<Item> MYCELIUM_DOOR = doubleBlock(TruedarknessModBlocks.MYCELIUM_DOOR);
	public static final RegistryObject<Item> MYCELIUM_TRAP_DOOR = block(TruedarknessModBlocks.MYCELIUM_TRAP_DOOR);
	public static final RegistryObject<Item> MYCELIUM_PRESSURE_PLATE = block(TruedarknessModBlocks.MYCELIUM_PRESSURE_PLATE);
	public static final RegistryObject<Item> MYCELIUM_BUTTON = block(TruedarknessModBlocks.MYCELIUM_BUTTON);
	public static final RegistryObject<Item> GLOW_FENCE_GATE = block(TruedarknessModBlocks.GLOW_FENCE_GATE);
	public static final RegistryObject<Item> GLOW_DOOR = doubleBlock(TruedarknessModBlocks.GLOW_DOOR);
	public static final RegistryObject<Item> GLOW_TRAP_DOOR = block(TruedarknessModBlocks.GLOW_TRAP_DOOR);
	public static final RegistryObject<Item> GLOW_PRESSURE_PLATE = block(TruedarknessModBlocks.GLOW_PRESSURE_PLATE);
	public static final RegistryObject<Item> GLOW_BUTTON = block(TruedarknessModBlocks.GLOW_BUTTON);
	public static final RegistryObject<Item> CRYING_FENCE_GATE = block(TruedarknessModBlocks.CRYING_FENCE_GATE);
	public static final RegistryObject<Item> CRYING_DOOR = doubleBlock(TruedarknessModBlocks.CRYING_DOOR);
	public static final RegistryObject<Item> CRYING_TRAP_DOOR = block(TruedarknessModBlocks.CRYING_TRAP_DOOR);
	public static final RegistryObject<Item> CRYING_PRESSURE_PLATE = block(TruedarknessModBlocks.CRYING_PRESSURE_PLATE);
	public static final RegistryObject<Item> CRYING_BUTTON = block(TruedarknessModBlocks.CRYING_BUTTON);
	public static final RegistryObject<Item> FAKE_FENCE_GATE = block(TruedarknessModBlocks.FAKE_FENCE_GATE);
	public static final RegistryObject<Item> FAKE_DOOR = doubleBlock(TruedarknessModBlocks.FAKE_DOOR);
	public static final RegistryObject<Item> FAKE_TRAP_DOOR = block(TruedarknessModBlocks.FAKE_TRAP_DOOR);
	public static final RegistryObject<Item> FAKE_PRESSURE_PLATE = block(TruedarknessModBlocks.FAKE_PRESSURE_PLATE);
	public static final RegistryObject<Item> FAKE_BUTTON = block(TruedarknessModBlocks.FAKE_BUTTON);
	public static final RegistryObject<Item> DRIED_FENCE_GATE = block(TruedarknessModBlocks.DRIED_FENCE_GATE);
	public static final RegistryObject<Item> DRIED_PRESSURE_PLATE = block(TruedarknessModBlocks.DRIED_PRESSURE_PLATE);
	public static final RegistryObject<Item> DRIED_BUTTON = block(TruedarknessModBlocks.DRIED_BUTTON);
	public static final RegistryObject<Item> OCEAN_SKREZHAL_PART = REGISTRY.register("ocean_skrezhal_part", () -> new OceanSkrezhalPartItem());
	public static final RegistryObject<Item> CAVE_SKREZHAL_PART = REGISTRY.register("cave_skrezhal_part", () -> new CaveSkrezhalPartItem());
	public static final RegistryObject<Item> SKREZHAL = REGISTRY.register("skrezhal", () -> new SkrezhalItem());
	public static final RegistryObject<Item> EMPTY_CHISELED_ANCIENT_GLASS_SHARD = REGISTRY.register("empty_chiseled_ancient_glass_shard", () -> new EmptyChiseledAncientGlassShardItem());
	public static final RegistryObject<Item> CHISELED_ANCIENT_GLASS_SHARD = REGISTRY.register("chiseled_ancient_glass_shard", () -> new ChiseledAncientGlassShardItem());
	public static final RegistryObject<Item> EMPTY_CHISELED_GLASS_SHARD = REGISTRY.register("empty_chiseled_glass_shard", () -> new EmptyChiseledGlassShardItem());
	public static final RegistryObject<Item> CHISELED_GLASS_SHARD = REGISTRY.register("chiseled_glass_shard", () -> new ChiseledGlassShardItem());
	public static final RegistryObject<Item> CHISELED_GLASS_SHARD_1 = REGISTRY.register("chiseled_glass_shard_1", () -> new ChiseledGlassShard1Item());
	public static final RegistryObject<Item> CHISELED_GLASS_SHARD_2 = REGISTRY.register("chiseled_glass_shard_2", () -> new ChiseledGlassShard2Item());
	public static final RegistryObject<Item> CHISELED_GLASS_SHARD_3 = REGISTRY.register("chiseled_glass_shard_3", () -> new ChiseledGlassShard3Item());
	public static final RegistryObject<Item> CHISELED_GLASS_SHARD_4 = REGISTRY.register("chiseled_glass_shard_4", () -> new ChiseledGlassShard4Item());
	public static final RegistryObject<Item> DISORIENT_DUST = REGISTRY.register("disorient_dust", () -> new DisorientDustItem());
	public static final RegistryObject<Item> SAND_REMNANTS = REGISTRY.register("sand_remnants", () -> new SandRemnantsItem());
	public static final RegistryObject<Item> ACCUSTONE_PEBBLES = REGISTRY.register("accustone_pebbles", () -> new AccustonePebblesItem());
	public static final RegistryObject<Item> FIREFLIES_BOTTLE = REGISTRY.register("fireflies_bottle", () -> new FirefliesbottleItem());
	public static final RegistryObject<Item> GRAPE = REGISTRY.register("grape", () -> new GrapeItem());
	public static final RegistryObject<Item> BLUEBERRY = REGISTRY.register("blueberry", () -> new BlueberryItem());
	public static final RegistryObject<Item> SWEET_HERBS = REGISTRY.register("sweet_herbs", () -> new SweetHerbsItem());
	public static final RegistryObject<Item> SOOTHING_HERBS = REGISTRY.register("soothing_herbs", () -> new SoothingHerbsItem());
	public static final RegistryObject<Item> FRUITS_AND_BERRIES = REGISTRY.register("fruits_and_berries", () -> new FruitsAndBerriesItem());
	public static final RegistryObject<Item> FOREIGN_ROOTS = REGISTRY.register("foreign_roots", () -> new ForeignRootsItem());
	public static final RegistryObject<Item> MEDICINAL_HERBS = REGISTRY.register("medicinal_herbs", () -> new MedicinalHerbsItem());
	public static final RegistryObject<Item> POTHOLDERS = REGISTRY.register("potholders", () -> new PotholdersItem());
	public static final RegistryObject<Item> COCOA = REGISTRY.register("cocoa", () -> new CocoaItem());
	public static final RegistryObject<Item> LAVENDER_PETAL = REGISTRY.register("lavender_petal", () -> new LavenderPetalItem());
	public static final RegistryObject<Item> GLOW_BERRY_JAM = REGISTRY.register("glow_berry_jam", () -> new GlowBerryJamItem());
	public static final RegistryObject<Item> BERRY_SALAD = REGISTRY.register("berry_salad", () -> new BerrySaladItem());
	public static final RegistryObject<Item> CRUSHED_BLUEBERRIES = REGISTRY.register("crushed_blueberries", () -> new CrushedBluberriesItem());
	public static final RegistryObject<Item> SWAMP_PLANTS_SALAT = REGISTRY.register("swamp_plants_salat", () -> new SwampPlantsSalatItem());
	public static final RegistryObject<Item> ANCIENT_REGULATION = REGISTRY.register("ancient_regulation", () -> new AncientRegulationItem());
	public static final RegistryObject<Item> REEL = REGISTRY.register("reel", () -> new ReelItem());
	public static final RegistryObject<Item> PHOTO = REGISTRY.register("photo", () -> new PhotoItem());
	public static final RegistryObject<Item> SANDGLASS = REGISTRY.register("sandglass", () -> new SandglassItem());
	public static final RegistryObject<Item> LETTER = REGISTRY.register("letter", () -> new LetterItem());
	public static final RegistryObject<Item> ANCIENT_PAPYRUS = REGISTRY.register("ancient_papyrus", () -> new AncientPapyrusItem());
	public static final RegistryObject<Item> ELDER_DOCUMENT = REGISTRY.register("elder_document", () -> new ElderDocumentItem());
	public static final RegistryObject<Item> DRINK_RECIPE = REGISTRY.register("drink_recipe", () -> new DrinkRecipeItem());
	public static final RegistryObject<Item> SIEVE = REGISTRY.register("sieve", () -> new SieveItem());
	public static final RegistryObject<Item> CROWN_HELMET = REGISTRY.register("crown_helmet", () -> new CrownItem.Helmet());
	public static final RegistryObject<Item> ELDER_TEAR = REGISTRY.register("elder_tear", () -> new ElderTearItem());
	public static final RegistryObject<Item> FLASK = REGISTRY.register("flask", () -> new FlaskItem());
	public static final RegistryObject<Item> CUP = REGISTRY.register("cup", () -> new CupItem());
	public static final RegistryObject<Item> GLASS_BOTTLE_CORRUPT = REGISTRY.register("glass_bottle_corrupt", () -> new GlassBottleCorruptItem());
	public static final RegistryObject<Item> SLICED_STEM = REGISTRY.register("sliced_stem", () -> new SlicedStemItem());
	public static final RegistryObject<Item> SMOKED_SLICED_STEM = REGISTRY.register("smoked_sliced_stem", () -> new SmokedSlicedStemItem());
	public static final RegistryObject<Item> POLLEN_FEATHER = REGISTRY.register("pollen_feather", () -> new PollenFeatherItem());
	public static final RegistryObject<Item> CRYER_TEAR = REGISTRY.register("cryer_tear", () -> new CryerPlasmItem());
	public static final RegistryObject<Item> SWAMP_COD = REGISTRY.register("swamp_cod", () -> new SwampCodItem());
	public static final RegistryObject<Item> SWAMP_POLLEN = REGISTRY.register("swamp_pollen", () -> new SwampPollenItem());
	public static final RegistryObject<Item> SHADDY_MELON_ITEM = REGISTRY.register("shaddy_melon_item", () -> new ShaddyMelonItemItem());
	public static final RegistryObject<Item> WASTELAND_WHEAT = REGISTRY.register("wasteland_wheat", () -> new WastelandWheatItem());
	public static final RegistryObject<Item> AQUATIC_AMULET_CHESTPLATE = REGISTRY.register("aquatic_amulet_chestplate", () -> new AquaticAmuletItem.Chestplate());
	public static final RegistryObject<Item> OCEAN_AMULET_CHESTPLATE = REGISTRY.register("ocean_amulet_chestplate", () -> new SeaHeartAmuletItem.Chestplate());
	public static final RegistryObject<Item> SWAMP_AMULET_CHESTPLATE = REGISTRY.register("swamp_amulet_chestplate", () -> new SwampAmuletItem.Chestplate());
	public static final RegistryObject<Item> ICEBERG_AMULET_CHESTPLATE = REGISTRY.register("iceberg_amulet_chestplate", () -> new IcebergAmuletItem.Chestplate());
	public static final RegistryObject<Item> CORAL_AMULET_CHESTPLATE = REGISTRY.register("coral_amulet_chestplate", () -> new CoralAmuletItem.Chestplate());
	public static final RegistryObject<Item> EMPTY_TREASURE_AMULET = REGISTRY.register("empty_treasure_amulet", () -> new EmptyTreasureAmuletItem());
	public static final RegistryObject<Item> CRACKED_TREASURE_AMULET = REGISTRY.register("cracked_treasure_amulet", () -> new CrackedTreasureAmuletItem());
	public static final RegistryObject<Item> AQUATIC_HELMET = REGISTRY.register("aquatic_helmet", () -> new AquaticItem.Helmet());
	public static final RegistryObject<Item> AQUATIC_BOOTS = REGISTRY.register("aquatic_boots", () -> new AquaticItem.Boots());
	public static final RegistryObject<Item> ENCORITE_SHARD = REGISTRY.register("encorite_shard", () -> new EncoriteShardItem());
	public static final RegistryObject<Item> DARK_CRYSTAL_SHARD = REGISTRY.register("dark_crystal_shard", () -> new GrimniteItem());
	public static final RegistryObject<Item> DARK_CRYSTAL = REGISTRY.register("dark_crystal", () -> new DarkCrystalClasterItem());
	public static final RegistryObject<Item> SWAMP_SLIMY = REGISTRY.register("swamp_slimy", () -> new SwampSlimyItem());
	public static final RegistryObject<Item> POOR_SLIME = REGISTRY.register("poor_slime", () -> new PoorSlimeItem());
	public static final RegistryObject<Item> SMALL_POOR_SLIME = REGISTRY.register("small_poor_slime", () -> new SmallPoorSlimeItem());
	public static final RegistryObject<Item> MUSHROOM_HAT = REGISTRY.register("mushroom_hat", () -> new MushroomHatItem());
	public static final RegistryObject<Item> CVETALIY_GRAIN = REGISTRY.register("cvetaliy_grain", () -> new CvetaliyGrainItem());
	public static final RegistryObject<Item> CVETALIT_SHARD = REGISTRY.register("cvetalit_shard", () -> new CvetalitShardItem());
	public static final RegistryObject<Item> CVETALIY = REGISTRY.register("cvetaliy", () -> new CvetaliyItem());
	public static final RegistryObject<Item> GLOWNITE_INGOT = REGISTRY.register("glownite_ingot", () -> new GlowniteIngotItem());
	public static final RegistryObject<Item> CVETALIY_CROWN_HELMET = REGISTRY.register("cvetaliy_crown_helmet", () -> new CvetaliyCrownItem.Helmet());
	public static final RegistryObject<Item> GRAMITE_SHARD = REGISTRY.register("gramite_shard", () -> new GramiteShardItem());
	public static final RegistryObject<Item> GRAMITE_STICK = REGISTRY.register("gramite_stick", () -> new GramiteStickItem());
	public static final RegistryObject<Item> GRAMITE_DAGGER = REGISTRY.register("gramite_dagger", () -> new GramiteDaggerItem());
	public static final RegistryObject<Item> GRAMITE_BATTLE_AXE = REGISTRY.register("gramite_battle_axe", () -> new GramiteBattleAxeItem());
	public static final RegistryObject<Item> GRAMITE_SHOVEL = REGISTRY.register("gramite_shovel", () -> new GramiteShovelItem());
	public static final RegistryObject<Item> GRAMITE_PICKAXE = REGISTRY.register("gramite_pickaxe", () -> new GramitePickaxeItem());
	public static final RegistryObject<Item> GRAMITE_HOE = REGISTRY.register("gramite_hoe", () -> new GramiteHoeItem());
	public static final RegistryObject<Item> FIRENITE_SCRAP = REGISTRY.register("firenite_scrap", () -> new FireniteScrapItem());
	public static final RegistryObject<Item> CORRUPTED_HELMET = REGISTRY.register("corrupted_helmet", () -> new CorruptedItem.Helmet());
	public static final RegistryObject<Item> CORRUPTED_CHESTPLATE = REGISTRY.register("corrupted_chestplate", () -> new CorruptedItem.Chestplate());
	public static final RegistryObject<Item> CORRUPTED_FIRENITE_SWORD = REGISTRY.register("corrupted_firenite_sword", () -> new CorruptedFireniteSwordItem());
	public static final RegistryObject<Item> RAW_FIRENITE = REGISTRY.register("raw_firenite", () -> new RawFireniteItem());
	public static final RegistryObject<Item> FIRENITE_INGOT = REGISTRY.register("firenite_ingot", () -> new FireniteIngotItem());
	public static final RegistryObject<Item> FIRENITE_SWORD = REGISTRY.register("firenite_sword", () -> new FireniteSwordItem());
	public static final RegistryObject<Item> FIRENITE_AXE = REGISTRY.register("firenite_axe", () -> new FireniteAxeItem());
	public static final RegistryObject<Item> FIRENITE_SHOVEL = REGISTRY.register("firenite_shovel", () -> new FireniteShovelItem());
	public static final RegistryObject<Item> FIRENITE_PICKAXE = REGISTRY.register("firenite_pickaxe", () -> new FirenitePickaxeItem());
	public static final RegistryObject<Item> FIRENITE_HOE = REGISTRY.register("firenite_hoe", () -> new FireniteHoeItem());
	public static final RegistryObject<Item> FIRENITE_ARMOR_HELMET = REGISTRY.register("firenite_armor_helmet", () -> new FireniteArmorItem.Helmet());
	public static final RegistryObject<Item> FIRENITE_ARMOR_CHESTPLATE = REGISTRY.register("firenite_armor_chestplate", () -> new FireniteArmorItem.Chestplate());
	public static final RegistryObject<Item> FIRENITE_ARMOR_LEGGINGS = REGISTRY.register("firenite_armor_leggings", () -> new FireniteArmorItem.Leggings());
	public static final RegistryObject<Item> FIRENITE_ARMOR_BOOTS = REGISTRY.register("firenite_armor_boots", () -> new FireniteArmorItem.Boots());
	public static final RegistryObject<Item> DARKNESS_SPRUCE_SHIELD = REGISTRY.register("darkness_spruce_shield", () -> new DarknessSpruceShieldItem());
	public static final RegistryObject<Item> SOULSTEAL_METAL = REGISTRY.register("soulsteal_metal", () -> new StoneMetalItem());
	public static final RegistryObject<Item> SOULSTEAL_INGOT = REGISTRY.register("soulsteal_ingot", () -> new SoulstealIngotItem());
	public static final RegistryObject<Item> SOULSTEAL_SHARD = REGISTRY.register("soulsteal_shard", () -> new SoulstealShardItem());
	public static final RegistryObject<Item> SOULSTEAL_NUGGET = REGISTRY.register("soulsteal_nugget", () -> new SoulstealNuggetItem());
	public static final RegistryObject<Item> SOULSTEAL_HEART = REGISTRY.register("soulsteal_heart", () -> new SoulstealHeartItem());
	public static final RegistryObject<Item> SOULSTEAL_WINGS = REGISTRY.register("soulsteal_wings", () -> new SoulstealWingsItem());
	public static final RegistryObject<Item> STONE_SPOOL = REGISTRY.register("stone_spool", () -> new StoneSpoolItem());
	public static final RegistryObject<Item> SOULSTEAL_SWORD = REGISTRY.register("soulsteal_sword", () -> new SoulstealSwordItem());
	public static final RegistryObject<Item> SOULSTEAL_AXE = REGISTRY.register("soulsteal_axe", () -> new SoulstealAxeItem());
	public static final RegistryObject<Item> SOULSTEAL_SHOVEL = REGISTRY.register("soulsteal_shovel", () -> new SoulstealShovelItem());
	public static final RegistryObject<Item> SOULSTEAL_PICKAXE = REGISTRY.register("soulsteal_pickaxe", () -> new SoulstealPickaxeItem());
	public static final RegistryObject<Item> SOULSTEAL_HOE = REGISTRY.register("soulsteal_hoe", () -> new SoulstealHoeItem());
	public static final RegistryObject<Item> SOULSTEAL_HAMMER = REGISTRY.register("soulsteal_hammer", () -> new SoulstealHammerItem());
	public static final RegistryObject<Item> SOULSTEAL_KNIFE = REGISTRY.register("soulsteal_knife", () -> new SoulstealKnifeItem());
	public static final RegistryObject<Item> ERIDIUM_BONE = REGISTRY.register("eridium_bone", () -> new EridiumBoneItem());
	public static final RegistryObject<Item> ERIDIUM_HEART = REGISTRY.register("eridium_heart", () -> new EridiumHeartItem());
	public static final RegistryObject<Item> ERIDIUM_SHARD = REGISTRY.register("eridium_shard", () -> new EridiumShardItem());
	public static final RegistryObject<Item> CURSED_MIRROR = REGISTRY.register("cursed_mirror", () -> new EridiumMirrorItem());
	public static final RegistryObject<Item> HEART_ERIDIUM = REGISTRY.register("heart_eridium", () -> new HeartEridiumItem());
	public static final RegistryObject<Item> CURSED_METAL = REGISTRY.register("cursed_metal", () -> new CursedMetalItem());
	public static final RegistryObject<Item> CURSED_BATTLE_AXE = REGISTRY.register("cursed_battle_axe", () -> new CursedBattleAxeItem());
	public static final RegistryObject<Item> BUBBLE_ROD = REGISTRY.register("bubble_rod", () -> new BubbleRodItem());
	public static final RegistryObject<Item> CORRUPTED_HAND_FANGS = REGISTRY.register("corrupted_hand_fangs", () -> new CorruptedHandFangsItem());
	public static final RegistryObject<Item> FANG_PICKAXE = REGISTRY.register("fang_pickaxe", () -> new FangPickaxeItem());
	public static final RegistryObject<Item> TOOL_FANG = REGISTRY.register("tool_fang", () -> new ToolFangItem());
	public static final RegistryObject<Item> CURSED_SWORD = REGISTRY.register("cursed_sword", () -> new CursedSwordItem());
	public static final RegistryObject<Item> CURSED_PAPYRUS = REGISTRY.register("cursed_papyrus", () -> new CursedPapyrusItem());
	public static final RegistryObject<Item> CORRUPTED_AMULET_CHESTPLATE = REGISTRY.register("corrupted_amulet_chestplate", () -> new CorruptedAmuletItem.Chestplate());
	public static final RegistryObject<Item> CORRUPTED_AXE = REGISTRY.register("corrupted_axe", () -> new CorruptedAxeItem());
	public static final RegistryObject<Item> GENERAL_SCALE = REGISTRY.register("general_scale", () -> new GeneralScaleItem());
	public static final RegistryObject<Item> GENERAL_CHESTPLATE = REGISTRY.register("general_chestplate", () -> new GeneralArmorItem.Chestplate());
	public static final RegistryObject<Item> GENERAL_LEGGINGS = REGISTRY.register("general_leggings", () -> new GeneralArmorItem.Leggings());
	public static final RegistryObject<Item> GENERAL_BOOTS = REGISTRY.register("general_boots", () -> new GeneralArmorItem.Boots());
	public static final RegistryObject<Item> GENERAL_KNIFE = REGISTRY.register("general_knife", () -> new GeneralKnifeItem());
	public static final RegistryObject<Item> AQUAMARINE_MIRROR = REGISTRY.register("aquamarine_mirror", () -> new AquamarineMirrorItem());
	public static final RegistryObject<Item> AQUAMARINE_COIN = REGISTRY.register("aquamarine_coin", () -> new AquamarineCoinItem());
	public static final RegistryObject<Item> CALM_AQUAMARINE = REGISTRY.register("calm_aquamarine", () -> new CalmAquamarineItem());
	public static final RegistryObject<Item> CRY_INGOT = REGISTRY.register("cry_ingot", () -> new CryIngotItem());
	public static final RegistryObject<Item> CRY_SWORD = REGISTRY.register("cry_sword", () -> new PhasmaSwordItem());
	public static final RegistryObject<Item> CRY_PICKAXE = REGISTRY.register("cry_pickaxe", () -> new CryPickaxeItem());
	public static final RegistryObject<Item> CRY_HAMMER = REGISTRY.register("cry_hammer", () -> new CryHammerItem());
	public static final RegistryObject<Item> REAL_GENERAL_SWORD = REGISTRY.register("real_general_sword", () -> new RealGeneralSwordItem());
	public static final RegistryObject<Item> GENERAL_REGULATION = REGISTRY.register("general_regulation", () -> new GeneralRegulationItem());
	public static final RegistryObject<Item> GENERAL_WINGS = REGISTRY.register("general_wings", () -> new GeneralWingsItem());
	public static final RegistryObject<Item> GENERAL_HEART = REGISTRY.register("general_heart", () -> new GeneralHeartItem());
	public static final RegistryObject<Item> GENERAL_MIRROR = REGISTRY.register("general_mirror", () -> new GeneralMirrorItem());
	public static final RegistryObject<Item> SOUL_GRAIN = REGISTRY.register("soul_grain", () -> new SoulGrainItem());
	public static final RegistryObject<Item> SOUL_CRYSTAL = REGISTRY.register("soul_crystal", () -> new SoulCrystalItem());
	public static final RegistryObject<Item> SOUL_BOTTLE = REGISTRY.register("soul_bottle", () -> new SoulBottleItem());
	public static final RegistryObject<Item> SOUL_STONE = REGISTRY.register("soul_stone", () -> new SoulStoneItem());
	public static final RegistryObject<Item> SOUL_SPOOL = REGISTRY.register("soul_spool", () -> new SoulSpoolItem());
	public static final RegistryObject<Item> SOUL_WINGS = REGISTRY.register("soul_wings", () -> new SoulWingsItem());
	public static final RegistryObject<Item> SOUL_HEART = REGISTRY.register("soul_heart", () -> new StoneHeartItem());
	public static final RegistryObject<Item> SOUL_MIRROR = REGISTRY.register("soul_mirror", () -> new AncientMirrorReinforceItem());
	public static final RegistryObject<Item> RAW_TRUDNITE = REGISTRY.register("raw_trudnite", () -> new RawTrudniteItem());
	public static final RegistryObject<Item> TRUDNITE_INGOT = REGISTRY.register("trudnite_ingot", () -> new TrudniteIngotItem());
	public static final RegistryObject<Item> TRUDNITE_HELMET = REGISTRY.register("trudnite_helmet", () -> new TrudniteItem.Helmet());
	public static final RegistryObject<Item> TRUDNITE_CHESTPLATE = REGISTRY.register("trudnite_chestplate", () -> new TrudniteItem.Chestplate());
	public static final RegistryObject<Item> TRUDNITE_LEGGINGS = REGISTRY.register("trudnite_leggings", () -> new TrudniteItem.Leggings());
	public static final RegistryObject<Item> TRUDNITE_BOOTS = REGISTRY.register("trudnite_boots", () -> new TrudniteItem.Boots());
	public static final RegistryObject<Item> METENITE_SHARD = REGISTRY.register("metenite_shard", () -> new MeteniteShardItem());
	public static final RegistryObject<Item> METENITE_CRYSTAL = REGISTRY.register("metenite_crystal", () -> new MeteniteCrystalItem());
	public static final RegistryObject<Item> METENITE_INGOT = REGISTRY.register("metenite_ingot", () -> new MeteniteIngotItem());
	public static final RegistryObject<Item> METENITE_HELMET = REGISTRY.register("metenite_helmet", () -> new MeteniteArmorItem.Helmet());
	public static final RegistryObject<Item> METENITE_CHESTPLATE = REGISTRY.register("metenite_chestplate", () -> new MeteniteArmorItem.Chestplate());
	public static final RegistryObject<Item> METENITE_LEGGINGS = REGISTRY.register("metenite_leggings", () -> new MeteniteArmorItem.Leggings());
	public static final RegistryObject<Item> METENITE_BOOTS = REGISTRY.register("metenite_boots", () -> new MeteniteArmorItem.Boots());
	public static final RegistryObject<Item> SCUIKED_APPLE = REGISTRY.register("scuiked_apple", () -> new ScilkedAppleItem());
	public static final RegistryObject<Item> SCULK_MANA_BOTTLE = REGISTRY.register("sculk_mana_bottle", () -> new SculkManaBottleItem());
	public static final RegistryObject<Item> SCULKED_SWORD = REGISTRY.register("sculked_sword", () -> new SkulkedSwordItem());
	public static final RegistryObject<Item> SCULKED_AXE = REGISTRY.register("sculked_axe", () -> new SkulkedAxeItem());
	public static final RegistryObject<Item> SCULKED_SHOVEL = REGISTRY.register("sculked_shovel", () -> new SkulkedShovelItem());
	public static final RegistryObject<Item> SCULKED_PICKAXE = REGISTRY.register("sculked_pickaxe", () -> new SkulkedPickaxeItem());
	public static final RegistryObject<Item> SCULKED_HOE = REGISTRY.register("sculked_hoe", () -> new SkulkedHoeItem());
	public static final RegistryObject<Item> ECHO_STONE = REGISTRY.register("echo_stone", () -> new EchoStoneItem());
	public static final RegistryObject<Item> ECHO_HARP = REGISTRY.register("echo_harp", () -> new EchoHarpItem());
	public static final RegistryObject<Item> ECHO_SANDGLASS = REGISTRY.register("echo_sandglass", () -> new SculkRingItem());
	public static final RegistryObject<Item> ECHO_HAMMER = REGISTRY.register("echo_hammer", () -> new EchoHammerItem());
	public static final RegistryObject<Item> SCULK_GRAIL = block(TruedarknessModBlocks.SCULK_GRAIL);
	public static final RegistryObject<Item> SOUL_MASTER = block(TruedarknessModBlocks.SOUL_MASTER);
	public static final RegistryObject<Item> ECHO_KNIFE = REGISTRY.register("echo_knife", () -> new EchoKnifeItem());
	public static final RegistryObject<Item> ECHO_PAPYRUS = REGISTRY.register("echo_papyrus", () -> new EchoPapyrusItem());
	public static final RegistryObject<Item> SCULK_RING = REGISTRY.register("sculk_ring", () -> new SculkRing1Item());
	public static final RegistryObject<Item> ECHO_FEATHER = REGISTRY.register("echo_feather", () -> new EchoFeatherItem());
	public static final RegistryObject<Item> ECHO_SPOOL = REGISTRY.register("echo_spool", () -> new EchoSpoolItem());
	public static final RegistryObject<Item> ECHO_WINGS = REGISTRY.register("echo_wings", () -> new EchoWingsItem());
	public static final RegistryObject<Item> ECHO_HEART = REGISTRY.register("echo_heart", () -> new EchoHeartItem());
	public static final RegistryObject<Item> ECHO_MIRROR = REGISTRY.register("echo_mirror", () -> new SwampMirrorItem());
	public static final RegistryObject<Item> SWAMP_COD_ENTITY_SPAWN_EGG = REGISTRY.register("swamp_cod_entity_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.SWAMP_COD_ENTITY, -8918019, -16249824, new Item.Properties()));
	public static final RegistryObject<Item> FLOW_SPAWN_EGG = REGISTRY.register("flow_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.FLOW, -16776916, -16770374, new Item.Properties()));
	public static final RegistryObject<Item> CORRUPTED_KNIGHT_SPAWN_EGG = REGISTRY.register("corrupted_knight_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.CORRUPTED_KNIGHT, -14870247, -13369237, new Item.Properties()));
	public static final RegistryObject<Item> CORRUPTED_HAND_SPAWN_EGG = REGISTRY.register("corrupted_hand_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.CORRUPTED_HAND, -15069902, -7194374, new Item.Properties()));
	public static final RegistryObject<Item> GENERAL_SPAWN_EGG = REGISTRY.register("general_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.GENERAL, -13418408, -7067431, new Item.Properties()));
	public static final RegistryObject<Item> ERIDIUM_ZOMBIE_SPAWN_EGG = REGISTRY.register("eridium_zombie_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.ERIDIUM_ZOMBIE, -15655366, -3901969, new Item.Properties()));
	public static final RegistryObject<Item> WASTE_RUNNER_SPAWN_EGG = REGISTRY.register("waste_runner_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.WASTE_RUNNER, -8158333, -10223453, new Item.Properties()));
	public static final RegistryObject<Item> ERIDIUM_GOLEM_SPAWN_EGG = REGISTRY.register("eridium_golem_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.ERIDIUM_GOLEM, -12058463, -16447193, new Item.Properties()));
	public static final RegistryObject<Item> CRYER_SPAWN_EGG = REGISTRY.register("cryer_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.CRYER, -16705255, -16726300, new Item.Properties()));
	public static final RegistryObject<Item> FUNGUM_SPAWN_EGG = REGISTRY.register("fungum_spawn_egg", () -> new ForgeSpawnEggItem(TruedarknessModEntities.FUNGUM, -11413010, -16376270, new Item.Properties()));
	public static final RegistryObject<Item> MUSIC_DISC_HOLLOW = REGISTRY.register("music_disc_hollow", () -> new MusicDiscHollowItem());
	public static final RegistryObject<Item> MUSIC_DISC_LAPIS = REGISTRY.register("music_disc_lapis", () -> new MusicDiscLapisItem());
	public static final RegistryObject<Item> MUSIC_DISC_RAIN = REGISTRY.register("music_disc_rain", () -> new MusicDiscRainItem());
	public static final RegistryObject<Item> MUSIC_DISC_TURQUOISE_FLOWER = REGISTRY.register("music_disc_turquoise_flower", () -> new MusicDiscTurquoiseFlowerItem());
	public static final RegistryObject<Item> MUSIC_DISC_FOREST_NIGHT = REGISTRY.register("music_disc_forest_night", () -> new MusicDiscForestNightItem());
	public static final RegistryObject<Item> MUSIC_DISC_HUMILITY = REGISTRY.register("music_disc_humility", () -> new MusicDiscHumilityItem());
	public static final RegistryObject<Item> SOULSTEAL_SMITHING_TEMPLATE = REGISTRY.register("soulsteal_smithing_template", () -> new SoulstealSmithingTemplateItem());
	public static final RegistryObject<Item> CUP_WATER = REGISTRY.register("cup_water", () -> new CupWaterItem());
	public static final RegistryObject<Item> WATER_FLASK = REGISTRY.register("water_flask", () -> new WaterFlaskItem());
	public static final RegistryObject<Item> LAVENDER_TEA = REGISTRY.register("lavender_tea", () -> new LavenderTeaItem());
	public static final RegistryObject<Item> LAVENDER_TEA_FLASK = REGISTRY.register("lavender_tea_flask", () -> new LavenderTeaFlaskItem());
	public static final RegistryObject<Item> FRUIT_TEA = REGISTRY.register("fruit_tea", () -> new FruitTeaItem());
	public static final RegistryObject<Item> FRUIT_TEA_FLASK = REGISTRY.register("fruit_tea_flask", () -> new FruitTeaFlaskItem());
	public static final RegistryObject<Item> COFFEE = REGISTRY.register("coffee", () -> new CoffeeItem());
	public static final RegistryObject<Item> COFFEE_FLASK = REGISTRY.register("coffee_flask", () -> new CoffeeFlaskItem());
	public static final RegistryObject<Item> BLUEBERRY_JUICE = REGISTRY.register("blueberry_juice", () -> new BluederryJuiceItem());
	public static final RegistryObject<Item> BLUEBERRY_JUICE_FLASK = REGISTRY.register("blueberry_juice_flask", () -> new BlueberryJuiceFlaskItem());
	public static final RegistryObject<Item> UNKNOWN_DRINK = REGISTRY.register("unknown_drink", () -> new UnknownDrinkItem());
	public static final RegistryObject<Item> UNKNOWN_DRINK_FLASK = REGISTRY.register("unknown_drink_flask", () -> new UnknownDrinkFlaskItem());
	public static final RegistryObject<Item> LIGHTED_VINE = block(TruedarknessModBlocks.LIGHTED_VINE);
	public static final RegistryObject<Item> LIGHTED_VINE_ACTIVE = block(TruedarknessModBlocks.LIGHTED_VINE_ACTIVE);
	public static final RegistryObject<Item> GLOW_FUNGUS_0 = block(TruedarknessModBlocks.GLOW_FUNGUS_0);
	public static final RegistryObject<Item> GLOW_FUNGUS_1 = block(TruedarknessModBlocks.GLOW_FUNGUS_1);
	public static final RegistryObject<Item> GLOW_FUNGUS_2 = block(TruedarknessModBlocks.GLOW_FUNGUS_2);
	public static final RegistryObject<Item> LIGHT_SHROOM_3 = block(TruedarknessModBlocks.LIGHT_SHROOM_3);
	public static final RegistryObject<Item> FIREFLIES_LIGHT = block(TruedarknessModBlocks.FIREFLIES_LIGHT);
	public static final RegistryObject<Item> LIGHTED_VINE_2 = block(TruedarknessModBlocks.LIGHTED_VINE_2);
	public static final RegistryObject<Item> LIGHT_MUSHROOMS_DISABLE = block(TruedarknessModBlocks.LIGHT_MUSHROOMS_DISABLE);
	public static final RegistryObject<Item> DISTABILIZATOR = REGISTRY.register("distabilizator", () -> new DistabilizatorItem());
	public static final RegistryObject<Item> BLOCK_OF_WRITING = block(TruedarknessModBlocks.BLOCK_OF_WRITING);
	public static final RegistryObject<Item> BLOCK_OF_WRITING_MINUS = block(TruedarknessModBlocks.BLOCK_OF_WRITING_MINUS);
	public static final RegistryObject<Item> BLOCK_OF_WRITING_PLUS = block(TruedarknessModBlocks.BLOCK_OF_WRITING_PLUS);
	public static final RegistryObject<Item> BLOCK_OF_WRITING_LAVENDER_PETAL = block(TruedarknessModBlocks.BLOCK_OF_WRITING_LAVENDER_PETAL);
	public static final RegistryObject<Item> BLOCK_OF_WRITING_COCOA = block(TruedarknessModBlocks.BLOCK_OF_WRITING_COCOA);
	public static final RegistryObject<Item> BLOCK_OF_WRITING_GLOW_BERRY_JAM = block(TruedarknessModBlocks.BLOCK_OF_WRITING_GLOW_BERRY_JAM);
	public static final RegistryObject<Item> BLOCK_OF_WRITING_BAG = block(TruedarknessModBlocks.BLOCK_OF_WRITING_BAG);
	public static final RegistryObject<Item> BLOCK_OF_WRITING_EQUALS = block(TruedarknessModBlocks.BLOCK_OF_WRITING_EQUALS);
	public static final RegistryObject<Item> SWAMP_SAND_LAYER = block(TruedarknessModBlocks.SWAMP_SAND_LAYER);
	public static final RegistryObject<Item> SAND_OF_MISSING_LAYER = block(TruedarknessModBlocks.SAND_OF_MISSING_LAYER);
	public static final RegistryObject<Item> SWAMP_KELP = block(TruedarknessModBlocks.SWAMP_KELP);
	public static final RegistryObject<Item> SWAMP_KELP_TOP = block(TruedarknessModBlocks.SWAMP_KELP_TOP);
	public static final RegistryObject<Item> SWAMP_SEAWEED = block(TruedarknessModBlocks.SWAMP_SEAWEED);
	public static final RegistryObject<Item> DARK_CRYSTAL_SWORD = REGISTRY.register("dark_crystal_sword", () -> new DarkCrystalSwordItem());
	public static final RegistryObject<Item> DARK_CRYSTAL_AXE = REGISTRY.register("dark_crystal_axe", () -> new DarkCrystalAxeItem());
	public static final RegistryObject<Item> DARK_CRYSTAL_SHOVEL = REGISTRY.register("dark_crystal_shovel", () -> new DarkCrystalShovelItem());
	public static final RegistryObject<Item> DARK_CRYSTAL_PICKAXE = REGISTRY.register("dark_crystal_pickaxe", () -> new DarkCrystalPickaxeItem());
	public static final RegistryObject<Item> DARK_CRYSTAL_HOE = REGISTRY.register("dark_crystal_hoe", () -> new DarkCrystalHoeItem());
	public static final RegistryObject<Item> CLAY_JUG = block(TruedarknessModBlocks.CLAY_JUG);
	public static final RegistryObject<Item> CLAY_JUG_2 = block(TruedarknessModBlocks.CLAY_JUG_2);
	public static final RegistryObject<Item> CLAY_JUG_3 = block(TruedarknessModBlocks.CLAY_JUG_3);
	public static final RegistryObject<Item> CLAY_JUG_4 = block(TruedarknessModBlocks.CLAY_JUG_4);
	public static final RegistryObject<Item> CLAY_JUG_5 = block(TruedarknessModBlocks.CLAY_JUG_5);
	public static final RegistryObject<Item> JUG_PATTERN = REGISTRY.register("jug_pattern", () -> new JugPatternItem());
	public static final RegistryObject<Item> LAVENDER_AZALEA_LEAVES = block(TruedarknessModBlocks.LAVENDER_AZALEA_LEAVES);
	public static final RegistryObject<Item> FROZEN_STEAL_KEY = REGISTRY.register("frozen_steal_key", () -> new FrozenStealKeyItem());
	public static final RegistryObject<Item> SAMOVAR_ACTIVE = block(TruedarknessModBlocks.SAMOVAR_ACTIVE);
	public static final RegistryObject<Item> KETTLE_FOR_SAMOVER = block(TruedarknessModBlocks.KETTLE_FOR_SAMOVER);
	public static final RegistryObject<Item> COPPER_KETTLE_FOR_SAMOVAR = block(TruedarknessModBlocks.COPPER_KETTLE_FOR_SAMOVAR);
	public static final RegistryObject<Item> LIGHT_MUSHROOM_TOP = block(TruedarknessModBlocks.LIGHT_MUSHROOM_TOP);
	public static final RegistryObject<Item> LIGHT_MUSHROOM_TOP_1 = block(TruedarknessModBlocks.LIGHT_MUSHROOM_TOP_1);
	public static final RegistryObject<Item> DRIED_SWAMP_KELP = REGISTRY.register("dried_swamp_kelp", () -> new DriedSwampKelpItem());
	public static final RegistryObject<Item> CHARGE_FEATHER = REGISTRY.register("charge_feather", () -> new ChargeFeatherItem());
	public static final RegistryObject<Item> SCULK_FEATHER_SPELL = REGISTRY.register("sculk_feather_spell", () -> new SculkFeatherItem());
	public static final RegistryObject<Item> CORRUPT_RUNE = block(TruedarknessModBlocks.CORRUPT_RUNE);
	public static final RegistryObject<Item> CORRUPT_RUNE_1 = block(TruedarknessModBlocks.CORRUPT_RUNE_1);
	public static final RegistryObject<Item> CORRUPT_RUNE_2 = block(TruedarknessModBlocks.CORRUPT_RUNE_2);
	public static final RegistryObject<Item> SHANDARAH = REGISTRY.register("shandarah", () -> new ShandarahItem());
	public static final RegistryObject<Item> CORRUPTED_SCULK_CATALYST_SPAWN = block(TruedarknessModBlocks.CORRUPTED_SCULK_CATALYST_SPAWN);
	public static final RegistryObject<Item> SWAMP_SAND_LAYER_1 = block(TruedarknessModBlocks.SWAMP_SAND_LAYER_1);
	public static final RegistryObject<Item> SWAMP_SAND_LAYER_2 = block(TruedarknessModBlocks.SWAMP_SAND_LAYER_2);
	public static final RegistryObject<Item> SAND_OF_MISSING_LAYER_1 = block(TruedarknessModBlocks.SAND_OF_MISSING_LAYER_1);
	public static final RegistryObject<Item> SAND_OF_MISSING_LAYER_2 = block(TruedarknessModBlocks.SAND_OF_MISSING_LAYER_2);
	public static final RegistryObject<Item> ANCIENT_MIRROR = REGISTRY.register("ancient_mirror", () -> new AncientMirrorItem());
	public static final RegistryObject<Item> ANCIENT_MIRROR_WILL = REGISTRY.register("ancient_mirror_will", () -> new AncientMirrorWillItem());
	public static final RegistryObject<Item> SOUL = REGISTRY.register("soul", () -> new SoulItem());
	public static final RegistryObject<Item> CORRUPTED_BUBBLE = block(TruedarknessModBlocks.CORRUPTED_BUBBLE);
	public static final RegistryObject<Item> SPORE_VINE_BLOCK = block(TruedarknessModBlocks.SPORE_VINE_BLOCK);
	public static final RegistryObject<Item> SPORE_VINE_0 = block(TruedarknessModBlocks.SPORE_VINE_0);
	public static final RegistryObject<Item> SPORE_VINE_1 = block(TruedarknessModBlocks.SPORE_VINE_1);
	public static final RegistryObject<Item> SPORE_VINE_2 = block(TruedarknessModBlocks.SPORE_VINE_2);
	public static final RegistryObject<Item> GLOW_FUNGUS_HAT_0 = block(TruedarknessModBlocks.GLOW_FUNGUS_HAT_0);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
